import {presets} from './families.mjs';
import {FamilyLayers} from './layers.mjs';
import {V,geometry,evaluate,optimize,optimizers,parse} from './math.mjs';
const $=id=>document.getElementById(id),svgNS='http://www.w3.org/2000/svg',{add:A,sub:S,mul:M,norm:N}=V;
const make=(tag,attrs={},text='')=>{let e=document.createElementNS(svgNS,tag);for(let [k,v]of Object.entries(attrs))e.setAttribute(k,v);if(text)e.textContent=text;return e;};
const num=x=>Number.isFinite(x)?Number(x.toPrecision(7)).toString():'—',vector=p=>p.map(num).join(', '),names={'TSZ[1]':'Equifacial Star (ES)','TSZ[2]':'Orthostar (OS)','TSZ[3]':'First Circumstar (CS1)'};
let triangle=[[0,0,0],[21,0,0],[16,12,0]],catalogue=[],extras=[],results=new Map(),filtered=[],pinned=null,hover=null,version=0,worker=null,timer=null,angle=-.8,elevation=.46,zoom=1,origin=[12,5,5],radius=15,drag=null,detailToken=0,lastDetail='',pending=0,error='',cache=new Map();
function selected(){return [...catalogue,...extras].find(s=>s.id===(hover||pinned));}
function color(index){let t=Math.max(0,Math.min(1,(index-10/13)/(5-10/13))),stops=[[112,186,255],[120,218,202],[255,224,138]],i=t<.5?0:1,u=t<.5?t*2:(t-.5)*2;return `rgb(${stops[i].map((v,j)=>Math.round(v+(stops[i+1][j]-v)*u)).join(',')})`;}
function project(p){let [x,y,z]=S(p,origin),u=Math.cos(angle)*x-Math.sin(angle)*y,v=Math.sin(angle)*x+Math.cos(angle)*y,d=Math.cos(elevation)*v+Math.sin(elevation)*z;return [450+u*260/radius*zoom,310+(Math.sin(elevation)*v-Math.cos(elevation)*z)*260/radius*zoom,d];}
function fit(baseOnly=false){let pts=baseOnly?[...triangle]:[...triangle,...filtered.map(s=>results.get(s.id)?.point).filter(Boolean),...layers.points()];let lo=pts.reduce((a,p)=>a.map((x,i)=>Math.min(x,p[i])),[Infinity,Infinity,Infinity]),hi=pts.reduce((a,p)=>a.map((x,i)=>Math.max(x,p[i])),[-Infinity,-Infinity,-Infinity]);origin=M(A(lo,hi),.5);radius=pts.reduce((r,p)=>Math.max(r,N(S(p,origin))),1e-6);zoom=1;render();}
function line(svg,a,b,attrs={}){let [x1,y1]=project(a),[x2,y2]=project(b);svg.append(make('line',{x1,y1,x2,y2,...attrs}));}
function render(){let svg=$('sky');svg.replaceChildren();layers.draw(project);let base=triangle.map(p=>project(p).slice(0,2).join(',')).join(' ');svg.append(make('polygon',{points:base,fill:'#233a50',stroke:'#8eabc4','stroke-width':1.4,'fill-opacity':'.25'}));let s=selected(),r=s&&results.get(s.id);if(r?.point){line(svg,r.point,r.foot,{stroke:'#fff3cc','stroke-width':1.4,'stroke-dasharray':'5 5'});let [x,y]=project(r.foot);svg.append(make('circle',{cx:x,cy:y,r:4,fill:'none',stroke:'#fff3cc','stroke-width':1.4}));for(let p of triangle)line(svg,p,r.point,{stroke:'#90a7bd','stroke-opacity':'.35','stroke-width':.8});}
 let unit=900/Math.max(1,svg.getBoundingClientRect().width),size=+$('size').value*unit;let stars=filtered.map(s=>({s,r:results.get(s.id)})).filter(v=>v.r?.point).sort((a,b)=>project(a.r.point)[2]-project(b.r.point)[2]);for(let {s,r}of stars){let [x,y]=project(r.point),active=s.id===(hover||pinned),rr=size*(s.special?1.25:1.1-.25*(s.index-10/13)/(5-10/13))*(active?1.6:1),g=make('g',{'data-id':s.id,style:'cursor:pointer',opacity:$('ghost').checked&&!s.special&&!active?.2:1});g.append(make('circle',{cx:x,cy:y,r:Math.max(rr,6*unit),fill:'transparent'}));g.append((s.opt||s.special)?make('path',{d:`M${x} ${y-rr-1} L${x+rr+1} ${y} L${x} ${y+rr+1} L${x-rr-1} ${y} Z`,fill:s.markerColor||color(s.index),stroke:active?'white':'#101f31','stroke-width':active?1.8:.8}):make('circle',{cx:x,cy:y,r:rr,fill:s.markerColor||color(s.index),stroke:active?'white':'#101f31','stroke-width':active?1.8:.6}));if(s.special&&$('center-labels').checked){g.append(make('text',{x:x+rr+4,y:y-rr-3,fill:s.markerColor||'#fff','font-size':12*unit,stroke:'#101f31','stroke-width':3*unit,'paint-order':'stroke','font-family':'system-ui'},s.shape==='center'?s.etc:s.name));}g.append(make('title',{},`${s.id} · ${s.name} · index ${s.exact}`));svg.append(g);}
 triangle.forEach((p,i)=>{let [x,y]=project(p);svg.append(make('circle',{cx:x,cy:y,r:4,fill:'#d7e4ef',stroke:'#101f31','stroke-width':1}));svg.append(make('text',{x:x+9,y:y+4,fill:'#e1eaf2','font-size':13,'font-family':'system-ui'},'ABC'[i]));});$('empty').textContent=error||(!stars.length&&!layers.points().length?'No real points match these filters.':'');}
function filter(){let q=$('search').value.toLowerCase();filtered=catalogue.filter(s=>s.index<=+$('cutoff').value+1e-10&&(s.opt?$('optimization').checked:$('constructive').checked)&&`${s.name} ${s.expression||''} ${s.etc} ${s.id}`.toLowerCase().includes(q));filtered.push(...extras.filter(s=>`${s.name} ${s.etc}`.toLowerCase().includes(q)));if(!filtered.some(s=>s.id===pinned))pinned=null;hover=null;let list=$('star-list');list.replaceChildren();for(let s of filtered){let option=document.createElement('option');option.value=s.id;let r=results.get(s.id);option.textContent=`${s.id} · ${s.opt?s.name:(s.etc?s.etc+' · ':'')+s.name} [${s.exact}]${r?.error?' — unavailable':!r?' — pending':''}`;list.append(option);}list.value=pinned||'';let real=filtered.filter(s=>results.get(s.id)?.point).length,unavailable=filtered.filter(s=>results.get(s.id)?.error).length;pending=filtered.length-real-unavailable;$('status').textContent=`${real} visible · ${unavailable} unavailable · ${pending} pending / ${filtered.length} selected${error?' · '+error:''}`;render();showDetails();}
function coordinates(){let box=$('coordinates');box.replaceChildren();triangle.forEach((p,i)=>{let row=document.createElement('div');row.className='coord-row';let name=document.createElement('strong');name.textContent='ABC'[i];row.append(name);p.forEach((v,j)=>{let l=document.createElement('label');l.textContent='xyz'[j];let input=document.createElement('input');input.type='number';input.step='.05';input.value=num(v);input.setAttribute('aria-label',`${'ABC'[i]} ${'xyz'[j]} coordinate`);input.addEventListener('change',()=>{let n=input.valueAsNumber;if(!Number.isFinite(n)){input.value=num(triangle[i][j]);return;}triangle[i][j]=n;recompute();});l.append(input);row.append(l);});box.append(row);});}
const editorMap=p=>[24+(p[0]+8)*312/38,211-(p[1]+8)*187/33];
function editor(){let svg=$('editor');svg.replaceChildren();svg.append(make('polygon',{points:triangle.map(p=>editorMap(p).join(',')).join(' '),fill:'#ddebf4',stroke:'#698aa2','stroke-width':1.5}));triangle.forEach((p,i)=>{let [x,y]=editorMap(p);svg.append(make('circle',{cx:x,cy:y,r:8,fill:'#244c68','data-vertex':i,style:'cursor:move'}));svg.append(make('text',{x:x+12,y:y+4,fill:'#244c68','font-size':13,'font-family':'system-ui'},'ABC'[i]));});svg.append(make('text',{x:10,y:15,fill:'#617487','font-size':10,'font-family':'system-ui'},'XY editor · use fields for coordinates outside the frame'));}
function stopWorker(){if(worker){worker.terminate();worker=null;}clearTimeout(timer);}
function launch(v){if(v!==version||!$('solve').checked||error)return;try{worker=new Worker('./worker.mjs',{type:'module'});worker.onmessage=({data})=>{if(data.version!==version)return;results.set(data.id,data.result);filter();};worker.onerror=()=>{for(let id of ['O-DGS','O-ERS','O-NFIS'])if(!results.has(id))results.set(id,{error:'Numerical worker failed; reload to retry'});filter();};worker.postMessage({version:v,triangle});}catch{for(let id of ['O-DGS','O-ERS','O-NFIS'])results.set(id,{error:'Web Workers are unavailable in this browser'});filter();}}
function recompute(initial=false,moving=false){version++;stopWorker();results.clear();error='';editor();coordinates();try{let g=geometry(triangle);$('triangle-metrics').textContent=`a, b, c = ${vector(g.sides)} · area = ${num(g.area)}`;for(let s of catalogue){if(!s.opt)results.set(s.id,evaluate(s.ast,triangle));else if(['O-IVS','O-CVS','O-EVS'].includes(s.id))results.set(s.id,optimize(s.id,triangle));else if(!$('solve').checked)results.set(s.id,{error:'Numerical calculation is paused'});}}catch(e){error=e.message;$('triangle-metrics').textContent=error;for(let s of catalogue)results.set(s.id,{error});}lastDetail='';layers.update(triangle,moving);filter();if(initial)fit();let v=version;timer=setTimeout(()=>launch(v),220);}
function textBlock(parent,tag,text,cls){let e=document.createElement(tag);e.textContent=text;if(cls)e.className=cls;parent.append(e);return e;}
async function showDetails(){let s=selected(),key=(s?.id||'')+':'+version+':'+JSON.stringify(s&&results.get(s.id));if(key===lastDetail)return;lastDetail=key;let token=++detailToken,body=$('detail-body');body.replaceChildren();$('detail-title').textContent=s?`${s.id} · ${s.name}`:'Select a star';if(!s){body.textContent='Hover over a marker or select a catalogue entry to inspect it. Clicking pins its perpendicular and information.';return;}let r=results.get(s.id);let facts=document.createElement('div');facts.className='facts';for(let [name,value]of [['Effective index',`${s.exact} ≈ ${num(s.index)}`],['Category',s.special?(s.shape==='center'?'Triangle center':'Strand landmark'):s.opt?'Optimization':'Constructive'],['ETC foot',s.etc||'No exact match supplied'],['Height',r?.point?num(r.height):'Unavailable'],['Definitions',s.special?'—':s.opt?'Optimization criterion':s.count]]){let f=document.createElement('div');textBlock(f,'span',name);textBlock(f,'strong',String(value));facts.append(f);}body.append(facts);if(r?.error)textBlock(body,'p',r.error);else if(!r)textBlock(body,'p','Calculating numerical star…');else{if(r.numerical)textBlock(body,'p',`Multistart local minimum · objective ${num(r.objective)} · ${r.converged?'simplex converged':'iteration limit reached; result is approximate'}`);textBlock(body,'p',`Apex (${vector(r.point)}) · foot (${vector(r.foot)}) · barycentrics (${vector(r.bary)})`);}
 textBlock(body,'div',s.opt||s.special?s.definition:s.expression,'formula');if(s.special)return;if(s.opt){textBlock(body,'p',s.formula);return;}let details=document.createElement('details');textBlock(details,'summary','Full definitions and symbolic formulae');body.append(details);details.addEventListener('toggle',async()=>{if(!details.open||details.dataset.loaded)return;details.dataset.loaded='true';let note=textBlock(details,'p','Loading original catalogue details…');try{let group=Math.floor((s.rank-1)/10);if(!cache.has(group))cache.set(group,fetch(`./data/details-${group}.json`).then(r=>{if(!r.ok)throw Error('Request failed');return r.json();}));let rows=await cache.get(group),d=rows.find(x=>x.Rank===s.rank);if(token!==detailToken)return;note.remove();textBlock(details,'h3','Coinciding definitions');textBlock(details,'div',d.Definitions.join('\n'),'formula');textBlock(details,'h3','Foot barycentrics (source formula)');textBlock(details,'div',d.FootBarycentricsNormalized,'formula');textBlock(details,'h3','Height (source formula)');textBlock(details,'div',d.HeightFormula,'formula');textBlock(details,'p','Here a = |BC|, b = |CA|, c = |AB|, p is perimeter, and r and R are the base triangle’s inradius and circumradius. Symbolic metadata is reproduced from the supplied catalogue; displayed coordinates are evaluated from the constructive expression.');}catch{note.textContent='Could not load full details. Reload the page to retry.';delete details.dataset.loaded;cache.clear();}});}
$('sky').addEventListener('pointerdown',e=>{drag={x:e.clientX,y:e.clientY,a:angle,b:elevation,moved:false,id:e.target.closest('[data-id]')?.dataset.id};$('sky').setPointerCapture(e.pointerId);});$('sky').addEventListener('pointermove',e=>{if(drag){let dx=e.clientX-drag.x,dy=e.clientY-drag.y;drag.moved ||=Math.hypot(dx,dy)>4;if(drag.moved){angle=drag.a+dx*.008;elevation=Math.max(-1.5,Math.min(1.5,drag.b+dy*.008));render();}}else{let id=e.target.closest('[data-id]')?.dataset.id||null;if(id!==hover){hover=id;render();showDetails();}}});$('sky').addEventListener('pointerup',()=>{if(drag&&!drag.moved&&drag.id){pinned=drag.id;$('star-list').value=pinned;}drag=null;render();showDetails();});$('sky').addEventListener('pointercancel',()=>{drag=null;});$('sky').addEventListener('pointerleave',()=>{if(!drag){hover=null;render();showDetails();}});$('sky').addEventListener('wheel',e=>{e.preventDefault();zoom=Math.max(.1,Math.min(30,zoom*Math.exp(-e.deltaY*.001)));render();},{passive:false});
let vertex=null;$('editor').addEventListener('pointerdown',e=>{let n=e.target.dataset.vertex;if(n===undefined)return;vertex=+n;$('editor').setPointerCapture(e.pointerId);});$('editor').addEventListener('pointermove',e=>{if(vertex===null)return;let rect=$('editor').getBoundingClientRect(),x=(e.clientX-rect.left)*360/rect.width,y=(e.clientY-rect.top)*235/rect.height;triangle[vertex][0]=Math.max(-8,Math.min(30,(x-24)*38/312-8));triangle[vertex][1]=Math.max(-8,Math.min(25,(211-y)*33/187-8));recompute(false,true);clearTimeout(timer);});function release(){if(vertex!==null){vertex=null;recompute();}}$('editor').addEventListener('pointerup',release);$('editor').addEventListener('pointercancel',release);
for(let id of ['cutoff','constructive','optimization'])$(id).addEventListener('change',()=>{filter();fit();});$('search').addEventListener('input',filter);$('solve').addEventListener('change',()=>recompute());$('size').addEventListener('input',()=>{$('size-value').textContent=$('size').value+' px';render();});$('star-list').addEventListener('change',()=>{pinned=$('star-list').value;hover=null;render();showDetails();});$('clear').addEventListener('click',()=>{pinned=hover=null;$('star-list').value='';render();showDetails();});$('fit').addEventListener('click',()=>fit());$('fit-base').addEventListener('click',()=>fit(true));$('top-view').addEventListener('click',()=>{if(error)return;let n=geometry(triangle).n;angle=Math.atan2(n[0],n[1]);elevation=Math.asin(n[2]);render();});$('reset-view').addEventListener('click',()=>{angle=-.8;elevation=.46;fit();});$('preset').addEventListener('change',()=>{triangle=presets.find(p=>p.id===$('preset').value).triangle.map(p=>p.slice());recompute(true);});

for(let p of presets)$('preset').add(new Option(p.name,p.id));$('preset').value='acute1';
const layers=new FamilyLayers(next=>{for(let e of extras)results.delete(e.id);extras=next;for(let e of extras)results.set(e.id,e.geometry);if(extras.some(e=>e.id==='F:probe')){pinned='F:probe';hover=null;}lastDetail='';filter();},()=>render(),()=>fit());

try{let response=await fetch('./data/catalogue.json');if(!response.ok)throw Error('Catalogue request failed');let data=await response.json();catalogue=[...data.map(d=>({id:'R'+d.Rank,rank:d.Rank,name:names[d.StarExpression]||d.StarExpression,expression:d.StarExpression,ast:parse(d.StarExpression),index:d.EffectiveIndexNumeric,exact:d.EffectiveIndexExact,etc:d.ETCIndex||'',count:d.CoincidingDefinitionCount})),...optimizers.map(o=>({...o,opt:true}))];recompute(true);}catch(e){$('status').textContent='Unable to load the catalogue. Please reload or use the downloadable source.';$('empty').textContent=e.message;}

new ResizeObserver(()=>render()).observe($('plot-wrap'));
