import {frame} from './families.mjs';
import {geometry,result,V} from './math.mjs';
const $=id=>document.getElementById(id),{add:A,sub:S,mul:M,dot:D}=V;
export function familyColor(family,k=1){if(family==='prekite')return '#365e97';if(family==='symmetric')return '#167747';let t=Math.max(0,Math.min(1,(k+3)/8)),a=family==='power'?[28,114,171]:[180,109,17],b=family==='power'?[128,60,151]:[174,42,68];return `rgb(${a.map((v,i)=>Math.round(v+(b[i]-v)*t)).join(',')})`;}
export class FamilyLayers {
 constructor(onChange,onRedraw,onReady=()=>{}){this.onReady=onReady;this.onChange=onChange;this.onRedraw=onRedraw;this.scene={lines:[],faces:[],stars:[],centers:[],notes:[]};this.triangle=null;this.version=0;this.worker=null;this.delay=null;this.canvas=$('family-canvas');this.ctx=this.canvas.getContext('2d');
  for(let id of ['power','eisenstein','prekite','symmetric','power-sheet','eisenstein-sheet','positive','quality'])$(id).addEventListener('change',()=>this.update(this.triangle));
  for(let id of ['power-k','eisenstein-k','extent'])$(id).addEventListener('input',()=>{this.outputs();this.update(this.triangle);});
  for(let id of ['surface-opacity','projections','ghost','center-labels','plane-grid','mesh-labels','height-contours'])$(id).addEventListener('input',()=>{this.outputs();this.onRedraw();});
  for(let id of ['centers-on','center-select','landmarks'])$(id).addEventListener('change',()=>this.emit());
  $('strand-select').addEventListener('change',()=>this.emit());$('strand-position').addEventListener('input',()=>this.emit());
  document.querySelectorAll('[data-family-k]').forEach(b=>b.addEventListener('click',()=>{let [family,k]=b.dataset.familyK.split(':');$(family+'-k').value=k;$(family).checked=true;this.outputs();this.update(this.triangle);}));
 }
 options(){return {power:$('power').checked,eisenstein:$('eisenstein').checked,prekite:$('prekite').checked,symmetric:$('symmetric').checked,powerSheet:$('power-sheet').checked,eisensteinSheet:$('eisenstein-sheet').checked,powerK:+$('power-k').value,eisensteinK:+$('eisenstein-k').value,clip:+$('extent').value,quality:$('quality').value,positive:$('positive').checked};}
 outputs(){for(let id of ['power-k','eisenstein-k','extent','surface-opacity'])$(id+'-value').textContent=id==='surface-opacity'?Math.round(+$(id).value*100)+'%':$(id).value;}
 update(triangle,dragging=false){if(!triangle)return;this.triangle=triangle.map(p=>p.slice());this.version++;if(this.worker)this.worker.terminate();clearTimeout(this.delay);this.scene={lines:[],faces:[],stars:[],centers:[],notes:[]};this.emit();$('family-status').textContent=dragging?'Release the vertex to update families.':'Calculating families…';if(!dragging){let version=this.version;this.delay=setTimeout(()=>{try{geometry(this.triangle);this.worker=new Worker('./family-worker.mjs',{type:'module'});this.worker.onmessage=({data})=>{if(data.version!==this.version)return;if(data.error){$('family-status').textContent=data.error;return;}this.scene=data.scene;this.fillControls();this.emit();this.onReady();};this.worker.onerror=()=>{$('family-status').textContent='Family calculation failed. Change a control or reload to retry.';};this.worker.postMessage({version,triangle:this.triangle,options:this.options()});}catch(e){$('family-status').textContent=e.message;}},180);}}
 fillControls(){let old=$('strand-select').value;$('strand-select').replaceChildren(new Option('No moving point',''));for(let l of this.scene.lines)l.segments.forEach((s,i)=>$('strand-select').add(new Option(`${l.name}${l.segments.length>1?' · graph '+(l.branches?.[i]||i+1):''}`,l.id+'|'+i)));$('strand-select').value=old;let unavailable=this.scene.lines.filter(l=>!l.segments.length).map(l=>l.name);$('family-status').textContent=`${this.scene.lines.filter(l=>l.segments.length).length} sampled strands · ${this.scene.faces.length} sheet triangles. Display window: ${this.options().clip} × longest base edge.${unavailable.length?' No visible real segment: '+unavailable.join('; ')+'.':''}`;$('family-notes').textContent=this.scene.notes.join(' ');}
 emit(){let extras=[];if(this.triangle){if($('landmarks').checked)for(let s of this.scene.stars)extras.push({...s,id:'F:'+s.id,special:true,exact:'—',index:0,etc:'',definition:s.description,shape:'star',markerColor:'#14733d'});if($('centers-on').checked){let ids=[...$('center-select').selectedOptions].map(o=>o.value);for(let s of this.scene.centers.filter(s=>ids.includes(s.id)))extras.push({...s,id:'C:'+s.id,name:`${s.id.replace('X','X(')}) · ${s.name}`,special:true,exact:'—',index:0,etc:s.id.replace('X','X(')+')',definition:'Triangle center in the current ABC plane. This is a center marker, not an apex star.',shape:'center',markerColor:'#334155'});}
 let [id,component]=$('strand-select').value.split('|'),line=this.scene.lines.find(l=>l.id===id),points=line?.segments[+component];if(points?.length){let i=Math.round(+$('strand-position').value/1000*(points.length-1)),p=points[i];extras.push({id:'F:probe',name:line.name+' · selected point',point:p,special:true,exact:'—',index:0,etc:'',definition:`Sample ${i+1} of ${points.length} on this connected component. Move the strand-position slider to inspect the apex, its perpendicular foot and the completed tetrahedron.`,shape:'probe',markerColor:'#101827'});$('strand-readout').textContent=`${line.name} · point ${i+1}/${points.length}`;}else $('strand-readout').textContent='Choose a strand component, then move along it.';
 for(let e of extras)e.geometry=result(e.point,this.triangle);}
 this.onChange(extras);this.onRedraw();}
 points(){return [...this.scene.lines.flatMap(l=>l.segments.flat()),...this.scene.faces.flatMap(f=>f.points)];}
 draw(project){let {ctx,canvas}=this;if(!ctx)return;let rect=canvas.getBoundingClientRect(),dpr=Math.min(2,globalThis.devicePixelRatio||1),w=Math.max(1,rect.width),h=Math.max(1,rect.height);if(canvas.width!==Math.round(w*dpr)||canvas.height!==Math.round(h*dpr)){canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);}ctx.setTransform(1,0,0,1,0,0);ctx.clearRect(0,0,canvas.width,canvas.height);let scale=Math.min(w/900,h/640);ctx.setTransform(dpr*scale,0,0,dpr*scale,dpr*(w-900*scale)/2,dpr*(h-640*scale)/2);
 const stroke=(pts,color,width,dash=[],alpha=1)=>{if(pts.length<2)return;ctx.beginPath();pts.forEach((p,i)=>{let q=project(p);i?ctx.lineTo(q[0],q[1]):ctx.moveTo(q[0],q[1]);});ctx.strokeStyle=color;ctx.lineWidth=width/scale;ctx.setLineDash(dash.map(x=>x/scale));ctx.globalAlpha=alpha;ctx.stroke();ctx.globalAlpha=1;};
 const label=(p,text,color)=>{let q=project(p);ctx.font=`${12/scale}px system-ui`;ctx.lineWidth=3/scale;ctx.strokeStyle='#fff';ctx.strokeText(text,q[0]+5/scale,q[1]-5/scale);ctx.fillStyle=color;ctx.fillText(text,q[0]+5/scale,q[1]-5/scale);};
 if(this.triangle&&$('plane-grid').checked){try{let f=frame(this.triangle),L=f.g.scale,step=10**Math.floor(Math.log10(L/5)),spacing=step*(L/step>30?5:L/step>15?2:1),extent=Math.ceil(Math.min(2,this.options().clip)*L/spacing)*spacing,n=Math.round(extent/spacing),p=(x,y)=>f.world([x/L,y/L,0]);for(let i=-n;i<=n;i++){let a=i*spacing;stroke([p(a,-extent),p(a,extent)],i===0?'#687887':'#d2dae1',i===0?1.2:.65);stroke([p(-extent,a),p(extent,a)],i===0?'#687887':'#d2dae1',i===0?1.2:.65);if(i&&i%2===0){label(p(a,0),String(Number(a.toPrecision(5))),'#586774');label(p(0,a),String(Number(a.toPrecision(5))),'#586774');}}label(p(extent,0),'u','#283e51');label(p(0,extent),'v','#283e51');label(p(0,0),'0','#283e51');}catch{}}
 let faces=this.scene.faces.map(f=>({...f,p:f.points.map(project)}));faces.sort((a,b)=>a.p.reduce((s,p)=>s+p[2],0)-b.p.reduce((s,p)=>s+p[2],0));ctx.globalAlpha=+$('surface-opacity').value;for(let f of faces){ctx.beginPath();f.p.forEach((p,i)=>i?ctx.lineTo(p[0],p[1]):ctx.moveTo(p[0],p[1]));ctx.closePath();ctx.fillStyle=familyColor(f.family,f.k);ctx.fill();}ctx.globalAlpha=1;
 let chosen=$('strand-select').value.split('|')[0],g;try{g=this.triangle&&geometry(this.triangle);}catch{}

 for(let l of this.scene.lines){let selected=l.id===chosen,color=familyColor(l.family,l.k),dash=l.family==='eisenstein'?[7,4]:[];for(let s of l.segments){if($('projections').checked&&g)stroke(s.map(p=>S(p,M(g.n,D(S(p,this.triangle[0]),g.n)))),color,.8,[2,4],.42);if(selected)stroke(s,'#fff',5);stroke(s,color,selected?2.8:l.emphasis?2:1.1,dash,selected||l.emphasis?1:.75);}if(g)for(let p of l.trace){let q=project(p);ctx.beginPath();ctx.arc(q[0],q[1],2.5/scale,0,2*Math.PI);ctx.fillStyle=color;ctx.fill();}}
 if($('height-contours').checked)for(let c of this.scene.contours||[]){stroke(c.points,'#536775',.7,[],.65);}
 if($('mesh-labels').checked){ctx.setLineDash([]);let boxes=[];const place=(p,text,color)=>{let q=project(p);if(q[0]<15||q[0]>865||q[1]<20||q[1]>605)return false;if(boxes.some(b=>Math.abs(q[0]-b[0])<85/scale&&Math.abs(q[1]-b[1])<19/scale))return false;label(p,text,color);boxes.push(q);return true;};for(let l of this.scene.lines)if(l.k!==null)l.segments.forEach((s,i)=>{for(let a of [.62,.85,.35,.12,.98])if(place(s[Math.min(s.length-1,Math.floor(a*s.length))],`k=${Number(l.k.toFixed(2))} [${l.branches?.[i]||i+1}]`,familyColor(l.family,l.k)))break;});for(let c of this.scene.contours||[])if(c.points.length>5){let text=`h=${Number(c.h.toPrecision(3))}`;for(let a of [.25,.5,.75])if(place(c.points[Math.floor(a*(c.points.length-1))],text,'#465660'))break;}}
 ctx.setLineDash([]);ctx.globalAlpha=1;
 }
}
