// Triangle Sky numerical port. Copyright (c) 2026 Ismail Hammoudeh. MIT.
// Complex, bilinear arithmetic preserves the source's analytic continuation.
class C { constructor(r,i=0){this.r=r;this.i=i;} }
const c=x=>x instanceof C?x:new C(x), add=(a,b)=>{a=c(a);b=c(b);return new C(a.r+b.r,a.i+b.i)}, neg=a=>{a=c(a);return new C(-a.r,-a.i)}, sub=(a,b)=>add(a,neg(b)), mul=(a,b)=>{a=c(a);b=c(b);return new C(a.r*b.r-a.i*b.i,a.r*b.i+a.i*b.r)}, div=(a,b)=>{a=c(a);b=c(b);let d=b.r*b.r+b.i*b.i;if(d<1e-28)throw Error('Singular construction');return new C((a.r*b.r+a.i*b.i)/d,(a.i*b.r-a.r*b.i)/d)}, abs=a=>{a=c(a);return Math.hypot(a.r,a.i)}, sqrt=a=>{a=c(a);let r=abs(a);return new C(Math.sqrt(Math.max(0,(r+a.r)/2)),(a.i<0?-1:1)*Math.sqrt(Math.max(0,(r-a.r)/2)))};
const va=(a,b)=>a.map((v,i)=>add(v,b[i])), vs=(a,b)=>a.map((v,i)=>sub(v,b[i])), vm=(a,k)=>a.map(v=>mul(v,k)), dot=(a,b)=>a.reduce((s,v,i)=>add(s,mul(v,b[i])),c(0)), cross=(a,b)=>[sub(mul(a[1],b[2]),mul(a[2],b[1])),sub(mul(a[2],b[0]),mul(a[0],b[2])),sub(mul(a[0],b[1]),mul(a[1],b[0]))], len=a=>sqrt(dot(a,a)), norm=a=>Math.hypot(...a.map(abs)), mean=a=>vm(a.reduce(va),1/a.length);
function solve(A,b){let m=A.map((r,i)=>[...r.map(c),c(b[i])]);for(let k=0;k<b.length;k++){let p=k;for(let i=k+1;i<b.length;i++)if(abs(m[i][k])>abs(m[p][k]))p=i;[m[k],m[p]]=[m[p],m[k]];let d=m[k][k];m[k]=m[k].map(v=>div(v,d));for(let i=0;i<b.length;i++)if(i!==k){let f=m[i][k];m[i]=m[i].map((v,j)=>sub(v,mul(f,m[k][j])));}}return m.map(r=>r.at(-1));}
function normal(t){let n=cross(vs(t[1],t[0]),vs(t[2],t[0]));return vm(n,div(1,len(n)));}
function area(t){return mul(.5,len(cross(vs(t[1],t[0]),vs(t[2],t[0]))));}
function circum(t){let [a,b,d]=t,u=vs(b,a),v=vs(d,a),n=cross(u,v);return solve([vm(u,2),vm(v,2),n],[sub(dot(b,b),dot(a,a)),sub(dot(d,d),dot(a,a)),dot(n,a)]);}
function center(i,t){let [a,b,d]=t;if(i===2)return mean(t);if(i===3)return circum(t);if(i===4)return vs(vm(mean(t),3),vm(circum(t),2));if(i===1){let w=[len(vs(b,d)),len(vs(d,a)),len(vs(a,b))];return vm(t.map((p,j)=>vm(p,w[j])).reduce(va),div(1,w.reduce(add)));}throw Error('Unknown triangle center');}
function tetra(i,t){if(t.length!==4)throw Error('Four vertices required');if(i===2)return mean(t);if(i===1){let w=t.map((_,j)=>area(t.filter((_,k)=>k!==j)));return vm(t.map((p,j)=>vm(p,w[j])).reduce(va),div(1,w.reduce(add)));}if(i===3){let p=t[0];return solve(t.slice(1).map(q=>vm(vs(q,p),2)),t.slice(1).map(q=>sub(dot(q,q),dot(p,p))));}throw Error('Unknown tetrahedral center');}
function simple(i,t){let [a,b,d]=t,n=normal(t);if(i===3)return mean([...t,simple(1,t)]);if(i===2){let h=center(4,t);return va(h,vm(n,sqrt(neg(dot(vs(a,h),vs(b,h))))));}if(i===1){let u=vs(b,a),v=vs(d,a),aa=dot(vs(b,d),vs(b,d)),bb=dot(v,v),cc=dot(u,u);let q=solve([[cc,dot(u,v)],[dot(u,v),bb]],[mul(.5,add(sub(cc,bb),aa)),mul(.5,add(sub(bb,cc),aa))]);let f=va(a,va(vm(u,q[0]),vm(v,q[1])));return va(f,vm(n,sqrt(sub(aa,norm(vs(f,a))**2))));}throw Error('Unknown star');}
export function parse(source){let tokens=source.match(/TS[A-Za-z]+|\d+|[\[\],]/g)||[];if(tokens.join('')!==source.replace(/\s/g,''))throw Error('Invalid expression');let pos=0;function next(){let h=tokens[pos++];if(/^\d+$/.test(h))return +h;if(!/^TS[A-Za-z]+$/.test(h))throw Error('Invalid expression');let a=[];if(tokens[pos]==='['){pos++;a.push(next());while(tokens[pos]===','){pos++;a.push(next());}if(tokens[pos++]!==']')throw Error('Missing bracket');}return [h,...a];}let ast=next();if(pos!==tokens.length)throw Error('Trailing expression');return ast;}
function evaluateAST(ast,t){if(typeof ast==='number')return ast;let [h,...a]=ast;switch(h){case 'TSA':return t[0];case 'TSB':return t[1];case 'TSC':return t[2];case 'TSX':return center(a[0],t);case 'TSZ':return simple(a[0],t);case 'TSY':return tetra(a[0],a.slice(1).map(e=>evaluateAST(e,t)));case 'TSConjugate':return evaluateAST(a[0],[t[0],t[2],t[1]]);default:throw Error('Unsupported expression: '+h);}}
// Normalize before evaluation to make tolerances invariant under translation/scale.
export const V={add:(a,b)=>a.map((x,i)=>x+b[i]),sub:(a,b)=>a.map((x,i)=>x-b[i]),mul:(a,s)=>a.map(x=>x*s),dot:(a,b)=>a.reduce((s,x,i)=>s+x*b[i],0),cross:(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]],norm:a=>Math.hypot(...a)};
const {add:A,sub:S,mul:M,dot:D,cross:X,norm:N}=V;
export function geometry(t){if(t.length!==3||t.some(p=>p.length!==3||p.some(x=>!Number.isFinite(x))))throw Error('Enter finite coordinates');let sides=[N(S(t[1],t[2])),N(S(t[2],t[0])),N(S(t[0],t[1]))],scale=Math.max(...sides),cross=X(S(t[1],t[0]),S(t[2],t[0])),twiceArea=N(cross);if(!scale||twiceArea/scale**2<1e-8)throw Error('The base triangle is degenerate; move a vertex away from the line.');let per=sides.reduce((a,b)=>a+b),n=M(cross,1/twiceArea),q=t.map(p=>S(p,t[0]).map(x=>x/scale)),o=A(t[0],M(circum(q.map(p=>p.map(c))).map(x=>x.r),scale)),inc=M(t.map((p,i)=>M(p,sides[i])).reduce(A),1/per);return {sides,scale,n,area:twiceArea/2,per,r:twiceArea/per,R:sides.reduce((a,b)=>a*b)/(2*twiceArea),o,inc};}
export function result(point,t,g=geometry(t)){let signed=D(S(point,t[0]),g.n),foot=S(point,M(g.n,signed)),u=S(t[1],t[0]),v=S(t[2],t[0]),w=S(foot,t[0]),uu=D(u,u),uv=D(u,v),vv=D(v,v),den=uu*vv-uv*uv,b=(D(w,u)*vv-D(w,v)*uv)/den,c=(D(w,v)*uu-D(w,u)*uv)/den;return {point,foot,height:Math.abs(signed),bary:[1-b-c,b,c]};}
export function evaluate(expression,t){try{let g=geometry(t),q=t.map(p=>M(S(p,t[0]),1/g.scale).map(c)),p=evaluateAST(typeof expression==='string'?parse(expression):expression,q);if(p.some(x=>!Number.isFinite(c(x).r)||!Number.isFinite(c(x).i)||Math.abs(c(x).i)>1e-7))return {error:'Non-real or undefined for this triangle'};return result(A(t[0],M(p.map(x=>c(x).r),g.scale)),t,g);}catch(e){return {error:e.message};}}
export const optimizers=[
{id:'O-IVS',name:'Insphere-Volume Star (IVS)',index:1.5,exact:'3/2',etc:'X(1)',definition:'Minimize surface area³ / volume².',formula:'h = 2√2 r'},
{id:'O-DGS',name:'Dihedral-Gram Star (DGS)',index:5/3,exact:'5/3',etc:'',definition:'Minimize Σ(cos θ − 1/3)² over the six internal dihedral angles.',formula:'Numerical local minimum'},
{id:'O-ERS',name:'Euler-Ratio Star (ERS)',index:1.75,exact:'7/4',etc:'',definition:'Minimize tetrahedral circumradius / inradius.',formula:'Numerical local minimum'},
{id:'O-EVS',name:'Edge-Variance Star (EVS)',index:2,exact:'2',etc:'X(3)',definition:'Minimize variance of the six edge lengths.',formula:'h = √((p/3)² − R²), when p > 3R'},
{id:'O-NFIS',name:'Normal-Frame-Isotropy Star (NFIS)',index:2,exact:'2',etc:'',definition:'Minimize Σ cos² θ over the six internal dihedral angles.',formula:'Numerical local minimum'},
{id:'O-CVS',name:'Circumsphere-Volume Star (CVS)',index:2.25,exact:'9/4',etc:'X(3)',definition:'Minimize circumsphere volume / tetrahedron volume.',formula:'h = √2 R'}];
function realSolve(a,b){return solve(a,b).map(x=>x.r);}
export function objective(id,t,p){try{let pts=[...t,p],normals=pts.map((omitted,i)=>{let [a,b,c]=pts.filter((_,j)=>j!==i),n=X(S(b,a),S(c,a)),l=N(n);if(l<1e-14)throw Error();if(D(n,S(omitted,a))>0)n=M(n,-1);return M(n,1/l);});let cos=[];for(let i=0;i<4;i++)for(let j=i+1;j<4;j++)cos.push(-D(normals[i],normals[j]));if(id==='O-DGS')return cos.reduce((s,c)=>s+(c-1/3)**2,0);if(id==='O-NFIS')return cos.reduce((s,c)=>s+c*c,0);let volume=Math.abs(D(S(t[1],t[0]),X(S(t[2],t[0]),S(p,t[0]))))/6,surface=pts.reduce((s,_,i)=>{let [a,b,c]=pts.filter((_,j)=>j!==i);return s+N(X(S(b,a),S(c,a)))/2;},0),o=realSolve(pts.slice(1).map(q=>M(S(q,pts[0]),2)),pts.slice(1).map(q=>D(q,q)-D(pts[0],pts[0])));return N(S(o,pts[0]))/(3*volume/surface);}catch{return 1e12;}}
export function nelderMead(f,start,max=650){let simplex=[start,...start.map((_,i)=>start.map((x,j)=>x+(i===j?.09:0)))].map(x=>({x,y:f(x)}));let converged=false;for(let iter=0;iter<max;iter++){simplex.sort((a,b)=>a.y-b.y);if(Math.max(...simplex.map(p=>N(S(p.x,simplex[0].x))))<1e-7){converged=true;break;}let cen=M(simplex.slice(0,3).map(p=>p.x).reduce(A),1/3),worst=simplex[3],trial=k=>{let x=A(cen,M(S(cen,worst.x),k));return {x,y:f(x)}},r=trial(1);if(r.y<simplex[0].y){let e=trial(2);simplex[3]=e.y<r.y?e:r;}else if(r.y<simplex[2].y)simplex[3]=r;else{let contraction=trial(r.y<worst.y?.5:-.5);if(contraction.y<Math.min(r.y,worst.y))simplex[3]=contraction;else simplex=simplex.map((p,i)=>{if(!i)return p;let x=M(A(p.x,simplex[0].x),.5);return{x,y:f(x)};});}}simplex.sort((a,b)=>a.y-b.y);return {...simplex[0],converged};}
export function optimize(id,t){try{let g=geometry(t),foot,h;if(id==='O-IVS'){foot=g.inc;h=2*Math.SQRT2*g.r;}else if(id==='O-CVS'){foot=g.o;h=Math.SQRT2*g.R;}else if(id==='O-EVS'){foot=g.o;let h2=(g.per/3)**2-g.R**2;if(h2<=0)return {error:'No positive real EVS height (p ≤ 3R)'};h=Math.sqrt(h2);}else{let tri=t.map(p=>M(S(p,t[0]),1/g.scale)),point=x=>A(tri.map((p,i)=>M(p,[x[0],x[1],1-x[0]-x[1]][i])).reduce(A),M(g.n,Math.exp(x[2]))),fun=x=>{let b=[x[0],x[1],1-x[0]-x[1]],pen=1e5*(b.reduce((s,v)=>s+Math.max(0,-2-v,v-3)**2,0)+Math.max(0,-4-x[2],x[2]-1.6)**2);return objective(id,tri,point(x))+pen;},a=g.sides[0]/g.per,b=g.sides[1]/g.per,starts=id==='O-ERS'?[[.38,.33,Math.log(.70)],[a,b,Math.log(.55)],[1/3,1/3,Math.log(.65)]]:id==='O-DGS'?[[.13,.41,Math.log(.57)],[a,b,Math.log(.52)],[1/3,1/3,Math.log(.60)]]:[[.12,.40,Math.log(.54)],[a,b,Math.log(.50)],[1/3,1/3,Math.log(.58)]];let best=starts.map(x=>nelderMead(fun,x)).sort((a,b)=>a.y-b.y)[0];if(!Number.isFinite(best.y)||best.y>=1e11)return {error:'Optimizer did not find a finite result'};let p=A(t[0],M(point(best.x),g.scale));return {...result(p,t,g),objective:objective(id,tri,point(best.x)),converged:best.converged,numerical:true};}return result(A(foot,M(g.n,h)),t,g);}catch(e){return {error:e.message};}}
