import {add,sub,mul,dot,mean,norm,area} from './geometry.mjs';
const $=id=>document.getElementById(id),canvas=$('plot'),ctx=canvas.getContext('2d');
const colors={orbit:'#74634d',edge:'#386ba5',transfer:'#138159',ball:'#b76820',hull:'#526170',chest:'#a87819',cp:'#3979ad',cnt:'#8e569c',heart:'#158368',para:'#a87819',bisector:'#8e569c',network:'#3979ad',stable:'#bd5275',combined:'#087b82',triangle:'#158368'};
const diagnostic=[[0,0],[21,0],[5,12]],presets={triangle:{'13–20–21 triangle':diagnostic,'Equilateral':[[0,0],[2,0],[1,Math.sqrt(3)]],'Thin isosceles':[[-1,0],[1,0],[0,.3]],'Scalene obtuse':[[-1,0],[1,0],[-.7,.5]]},four:{'Triangle + its centroid':[...diagnostic,[26/3,4]],'Bundle planar example':[[0,0],[4,0],[3,2],[0,3]],'Convex quadrilateral':[[0,0],[6,.2],[4.7,4],[.5,3]],'Parallelogram':[[0,0],[5,0],[6,3],[1,3]],'Independent bisector':[[0,0],[4,7],[2,4],[3,3]]},tetra:{'Bundle tetrahedron':[[0,0,0],[4,0,0],[0,3,0],[1,1,2]],'Face-pyramid counterexample':[[1,0,0],[-.5,Math.sqrt(3)/2,0],[-.5,-Math.sqrt(3)/2,0],[1,0,1]],'Generic tetrahedron':[[0,0,0],[2,0,0],[.3,1.8,0],[.5,.6,2.2]],'Regular tetrahedron':[[1,1,1],[1,-1,-1],[-1,1,-1],[-1,-1,1]],'Flat but nondegenerate':[[0,0,0],[2,0,0],[.3,1.8,0],[.5,.6,.22]]}};
const optionSets={triangle:[['chest','Standard chest',true],['heart','Attractive inner hull',true],['cp','Characteristic strips',false],['cnt','Internal Napoleon triangle',false],['centers','Show center points',true]],four:[['para','Parallelogram strips',true],['bisector','Useful bisectors',true],['network','Two-order network',true],['orbit','Involution orbit bounds',false],['edge','Edge-projection slabs',true],['transfer','Centroid transfer (no axiom)',true],['ball','Diameter balls (power family)',false],['stable','Absorption (conditional)',false],['combined','Show intersection',true],['triangle','Standard chest of A,B,C',false]],tetra:[['para','Opposite-edge slabs',true],['bisector','Useful bisector planes',true],['orbit','Involution orbit bounds',false],['edge','Edge-projection slabs',true],['transfer','Face-centroid transfer',true],['ball','Diameter balls (power family)',false]]};
const theory={triangle:'A chest contains every attractive center. The standard triangle chest intersects the triangle, the three side-normal strips, and the anticomplementary triangle of the internal Napoleon centroids. It shrinks to the centroid for an equilateral triangle. The green polygon is an inner approximation from the proved attractive families described below.',four:'Parallelogram: translate one pair until its midpoint coincides with the other pair’s midpoint, then restore both vertices in parallel. Bisectors: project the other two points onto a pair’s bisector when they lie on the same side, then restore them in parallel. Network: start from an equilateral triangle with a fourth point at its center, keep the intermediate center in both motion orders, and minimize projections over its chest. Stability adds X₄(A,B,C,X₃)=X₃. For each omitted point, range X₃ over the remaining triangle’s standard chest, form the union of the valid half-planes, intersect the four clauses, then take a convex hull.',tetra:'Opposite-edge slabs: each of the three pair partitions gives two midpoint planes perpendicular to the line joining the pair midpoints. Parallel restoration from a centrally symmetric, possibly flat predecessor proves the slab. Useful bisector planes use reflection and same-sided parallel restoration, exactly as in the plane. Intersect these half-spaces with the tetrahedron. The polyhedron is a certified outer construction, not an assertion of optimality. Plane intersections and volume use numerical tolerances.'};
theory.four += ' Revision 2: edge-projection slabs place n·X between the minimum and maximum of the pair midpoint and remaining-point projections, using reflection and parallel restoration. Centroid insertion is unconditional: Y(P)=X(P,G(P)) is attractive. Restoring the omitted vertex gives a supporting half-plane; when D=G(ABC), the whole standard chest transfers. Diameter balls use a different, proved insertion inequality for coherent convex power means only; 64 sampled support directions enclose the curved region. The default intersection is unconditional. No claim of optimality is made.';
theory.tetra += ' Revision 2 adds edge-projection slabs and face-centroid transfer. A face pyramid over a triangle chest is NOT generally valid (see the counterexample preset). The optional diameter-ball construction is valid for coherent power means in the universal attractive interval, not for every attractive map. Its 26 sampled support normals give an outer polyhedral approximation. Recursive 3D network optimization is not implemented in this preview.';
let mode='triangle',points=structuredClone(diagnostic),on={},data=null,error='',busy=false,seq=0,pending=false,view={center:[10.5,6],scale:25},yaw=.55,pitch=.4,drag=null,hover=[],width=900,height=550;
const worker=new Worker(new URL('./worker.mjs',import.meta.url),{type:'module'});
function request(){seq++;pending=true;dispatch();}
function dispatch(){if(busy||!pending)return;busy=true;pending=false;$('status').textContent='Calculating…';worker.postMessage({id:seq,mode,points,on});}
worker.onmessage=({data:r})=>{busy=false;if(r.id===seq){error=r.error||'';data=r.error?null:r;draw();metrics();$('status').textContent=error||(mode==='tetra'?'Drag empty space to rotate. Drag a vertex in the screen plane.':mode==='triangle'?`${r.result.heart.centers.length} evaluated centers · ${r.result.heart.poly.length} inner-hull vertices${r.result.heart.failed?' · '+r.result.heart.failed+' unresolved samples omitted':''}`:`${r.result.pairs.length} useful bisectors · ${r.result.scenarios} network scenarios${r.result.skipped?' · '+r.result.skipped+' redundant or unresolved stages skipped':''}`);}dispatch();};
worker.onerror=e=>{$('status').textContent='Calculation error. Reload the page to retry.';busy=false;};
function options(){on=Object.fromEntries(optionSets[mode].map(([k,l,v])=>[k,v]));$('options').innerHTML=optionSets[mode].map(([k,l,v])=>`<label><input type="checkbox" data-opt="${k}" ${v?'checked':''}><span><span class="swatch" style="color:${colors[k]||colors.heart}"></span>${l}</span></label>`).join('');$('options').querySelectorAll('input').forEach(input=>input.onchange=()=>{on[input.dataset.opt]=input.checked;if(mode==='triangle')draw();else request();});$('theory').innerHTML=`<p>${theory[mode]}</p>`;$('instructions').textContent=mode==='tetra'?'Drag empty space to rotate. Drag a vertex parallel to the screen. Edit x, y, z below for exact placement. Scroll to zoom.':'Drag any vertex. Scroll to zoom. The coordinate scales stay equal. Edit coordinates below for exact placement.';$('preset').innerHTML=Object.keys(presets[mode]).map(k=>`<option>${k}</option>`).join('');}
function loadPreset(){points=structuredClone(presets[mode][$('preset').value]);data=null;error='';fit();coords();request();}
function coords(){let dim=mode==='tetra'?3:2;$('coordinates').innerHTML=points.map((p,i)=>`<div class="coord-row"><strong>${'ABCD'[i]}</strong>${p.map((v,j)=>`<input type="number" step="0.01" value="${+v.toFixed(6)}" aria-label="${'ABCD'[i]} ${'xyz'[j]}" data-i="${i}" data-j="${j}">`).join('')}</div>`).join('');$('coordinates').querySelectorAll('input').forEach(el=>el.onchange=()=>{let v=Number(el.value);if(!Number.isFinite(v)||Math.abs(v)>1e8){coords();return;}points[+el.dataset.i][+el.dataset.j]=v;request();draw();});}
function camera(p){let cy=Math.cos(yaw),sy=Math.sin(yaw),cp=Math.cos(pitch),sp=Math.sin(pitch);return [cy*p[0]+sy*p[2],-sp*sy*p[0]+cp*p[1]+sp*cy*p[2],-cp*sy*p[0]-sp*p[1]+cp*cy*p[2]];}
function project(p){if(mode==='tetra'){let q=camera(sub(p,view.center));return [width/2+q[0]*view.scale,height/2-q[1]*view.scale,q[2]];}return [width/2+(p[0]-view.center[0])*view.scale,height/2-(p[1]-view.center[1])*view.scale,0];}
function fit(){view.center=mean(points);let r=Math.max(...points.map(p=>norm(sub(p,view.center))));view.scale=Math.min(width,height)/Math.max(r*2.5,1e-6);if(mode!=='tetra'){let xs=points.map(p=>p[0]),ys=points.map(p=>p[1]);view.center=[(Math.min(...xs)+Math.max(...xs))/2,(Math.min(...ys)+Math.max(...ys))/2];view.scale=Math.min((width-90)/Math.max(1e-7,Math.max(...xs)-Math.min(...xs)),(height-90)/Math.max(1e-7,Math.max(...ys)-Math.min(...ys)));}draw();}
const world=p=>add(data.g,mul(p,data.s));
function path(poly,color,fill=true,dash=false,lw=2){if(!poly?.length)return;let q=poly.map(project);ctx.beginPath();ctx.moveTo(q[0][0],q[0][1]);for(let v of q.slice(1))ctx.lineTo(v[0],v[1]);if(q.length>2)ctx.closePath();ctx.setLineDash(dash?[6,5]:[]);ctx.strokeStyle=color;ctx.lineWidth=lw;if(fill&&q.length>2){ctx.fillStyle=color+'24';ctx.fill();}ctx.stroke();ctx.setLineDash([]);if(q.length===1){ctx.fillStyle=color;ctx.beginPath();ctx.arc(q[0][0],q[0][1],5,0,2*Math.PI);ctx.fill();}}
function grid(){if(mode==='tetra')return;let span=width/view.scale,unit=10**Math.floor(Math.log10(span/8)),step=span/unit>16?unit*2:unit;let x0=view.center[0]-width/(2*view.scale),x1=x0+span,y0=view.center[1]-height/(2*view.scale),y1=y0+height/view.scale;ctx.font='12px system-ui';ctx.fillStyle='#697584';for(let x=Math.ceil(x0/step)*step;x<=x1;x+=step){let a=project([x,y0]),b=project([x,y1]);ctx.strokeStyle='#e1e6eb';ctx.lineWidth=.7;ctx.beginPath();ctx.moveTo(...a.slice(0,2));ctx.lineTo(...b.slice(0,2));ctx.stroke();ctx.fillText(+x.toPrecision(5),a[0]+3,height-29);}for(let y=Math.ceil(y0/step)*step;y<=y1;y+=step){let a=project([x0,y]),b=project([x1,y]);ctx.strokeStyle='#e1e6eb';ctx.beginPath();ctx.moveTo(...a.slice(0,2));ctx.lineTo(...b.slice(0,2));ctx.stroke();ctx.fillText(+y.toPrecision(5),5,a[1]-3);}}
function draw(){ctx.clearRect(0,0,width,height);hover=[];grid();let legend=[];if(data&&data.mode===mode){let d=data.result;if(mode==='triangle'){for(let [k,poly] of [['cp',d.cp],['cnt',d.cnt],['chest',d.poly],['heart',d.heart.poly]])if(on[k]){path(poly.map(world),colors[k],true,k==='cp');legend.push([colors[k],{cp:'Strips clipped to triangle',cnt:'Internal Napoleon',chest:'Standard chest',heart:'Attractive inner hull'}[k]]);}if(on.centers)for(let c of d.heart.centers){let q=project(world(c.point));ctx.fillStyle=colors.heart;ctx.beginPath();ctx.arc(q[0],q[1],3,0,2*Math.PI);ctx.fill();hover.push({x:q[0],y:q[1],text:c.name});}path(points,colors.hull,false,false,1.6);}else if(mode==='four'){for(let [k,poly] of [['para',d.para.poly],['bisector',d.bisector],['network',d.network],['orbit',d.orbit],['edge',d.edge],['transfer',d.transfer],['ball',d.ball],['stable',d.stable],['triangle',d.triangle],['combined',d.combined]])if(on[k]){path(poly.map(world),colors[k],k==='combined',k==='triangle',k==='combined'?3:1.8);legend.push([colors[k],{orbit:'Involution orbit bounds',edge:'Edge slabs',transfer:'Centroid transfer',ball:'Diameter balls (conditional)',para:'Parallelogram',bisector:'Bisectors',network:'Network',stable:'Stability (conditional)',triangle:'ABC chest only',combined:'Selected intersection'}[k]]);}path(d.hull.map(world),colors.hull,false);}else{let faces=d.faces.map(f=>f.map(world));faces.sort((a,b)=>project(mean(a))[2]-project(mean(b))[2]);for(let f of faces)path(f,colors.combined,true,false,1.3);if(!d.faces.length&&d.vertices.length){let v=d.vertices.map(world),g=project(mean(v));v.sort((a,b)=>Math.atan2(project(a)[1]-g[1],project(a)[0]-g[0])-Math.atan2(project(b)[1]-g[1],project(b)[0]-g[0]));path(v,colors.combined,true);}for(let i=0;i<4;i++)for(let j=i+1;j<4;j++)path([points[i],points[j]],colors.hull,false,false,1.2);legend.push([colors.combined,'Selected 3D chest'],[colors.hull,'Tetrahedron']);}}
  points.forEach((p,i)=>{let [x,y]=project(p);ctx.beginPath();ctx.arc(x,y,7,0,Math.PI*2);ctx.fillStyle=i===3?'#bd5275':'#243849';ctx.fill();ctx.strokeStyle='#ffffff';ctx.lineWidth=2;ctx.stroke();ctx.font='bold 15px system-ui';ctx.fillStyle='#243849';ctx.fillText('ABCD'[i],x+11,y-10);});$('legend').innerHTML=legend.map(([c,l])=>`<span><span class="swatch" style="color:${c}"></span>${l}</span>`).join('');}
function metrics(){if(!data){$('metrics').textContent=error;return;}let d=data.result,rows=[],base=mode==='tetra'?d.base.volume:d.baseArea;const row=(label,m,n)=>{let ratio=100*m/base;rows.push(`<tr><td>${label}</td><td>${n}</td><td>${ratio.toFixed(4)}%</td><td>${(100-ratio).toFixed(4)}%</td></tr>`);};if(mode==='triangle'){row('Standard chest',area(d.poly),d.poly.length);row('Attractive inner hull',area(d.heart.poly),d.heart.poly.length);$('measure-note').textContent='Area retained. The inner hull is a lower estimate of the Heart.';}else if(mode==='four'){for(let [k,label,poly] of [['para','Parallelogram',d.para.poly],['bisector','Bisectors alone',d.bisector],['network','Network alone',d.network],['orbit','Orbit bounds alone',d.orbit],['edge','Edge slabs alone',d.edge],['transfer','Centroid transfer alone',d.transfer],['ball','Diameter balls (conditional)',d.ball],['stable','Absorption alone (conditional)',d.stable]])if(on[k])row(label,area(poly),poly.length);row(on.ball||on.stable?'Conditional intersection':'Unconditional intersection',area(d.combined),d.combined.length);rows[rows.length-1]=rows.at(-1).replace('<tr>','<tr class="total">');$('measure-note').textContent='Each method alone includes the hull. Intersection uses all checked methods.';}else{if(on.para)row('Opposite-edge slabs',d.para.volume,d.para.vertices.length);if(on.bisector)row('Bisector planes',d.bi.volume,d.bi.vertices.length);for(let [k,label] of [['edge','Edge slabs alone'],['transfer','Centroid transfer alone'],['ball','Diameter balls (conditional)']])if(on[k]&&d[k])row(label,d[k].volume,d[k].vertices.length);row(on.ball?'Conditional 3D intersection':'Unconditional 3D intersection',d.volume,d.vertices.length);$('measure-note').textContent=`Volume retained · ${d.faces.length} chest faces · ${d.bisectors} useful bisectors`;} $('metrics').innerHTML=`<table><thead><tr><th>Region</th><th>Vertices</th><th>Retained</th><th>Outside region</th></tr></thead><tbody>${rows.join('')}</tbody></table>`;}
function eventPos(e){let r=canvas.getBoundingClientRect();return [e.clientX-r.left,e.clientY-r.top];}
canvas.onpointerdown=e=>{let q=eventPos(e),idx=points.findIndex(p=>norm(sub(project(p).slice(0,2),q))<17);drag={idx,start:q,point:idx>=0?[...points[idx]]:null,yaw,pitch,center:[...view.center]};canvas.setPointerCapture(e.pointerId);$('tooltip').hidden=true;};
canvas.onpointermove=e=>{let q=eventPos(e);if(drag){let dx=(q[0]-drag.start[0])/view.scale,dy=-(q[1]-drag.start[1])/view.scale;if(drag.idx>=0){if(mode==='tetra'){let cy=Math.cos(yaw),sy=Math.sin(yaw),cp=Math.cos(pitch),sp=Math.sin(pitch);points[drag.idx]=add(drag.point,[cy*dx-sp*sy*dy,cp*dy,sy*dx+sp*cy*dy]);}else points[drag.idx]=add(drag.point,[dx,dy]);request();}else if(mode==='tetra'){yaw=drag.yaw+(q[0]-drag.start[0])*.007;pitch=Math.max(-1.5,Math.min(1.5,drag.pitch+(q[1]-drag.start[1])*.007));}else view.center=sub(drag.center,[dx,dy]);draw();return;}let items=hover.filter(h=>Math.hypot(h.x-q[0],h.y-q[1])<10),tip=$('tooltip');tip.hidden=!items.length;if(items.length){tip.textContent=items.slice(0,4).map(h=>h.text).join(' / ');tip.style.left=Math.min(width-265,q[0]+15)+'px';tip.style.top=Math.max(5,q[1]-40)+'px';}canvas.style.cursor=points.some(p=>norm(sub(project(p).slice(0,2),q))<17)?'grab':mode==='tetra'?'move':'crosshair';};
function release(){if(drag){drag=null;coords();}}canvas.onpointerup=release;canvas.onpointercancel=release;canvas.onlostpointercapture=release;canvas.onpointerleave=()=>{$('tooltip').hidden=true;};canvas.onwheel=e=>{e.preventDefault();view.scale=Math.max(1e-5,Math.min(1e8,view.scale*Math.exp(-e.deltaY*.001)));draw();};canvas.onkeydown=e=>{if(e.key==='0')fit();if(mode==='tetra'&&e.key.startsWith('Arrow')){e.preventDefault();if(e.key==='ArrowLeft')yaw-=.1;if(e.key==='ArrowRight')yaw+=.1;if(e.key==='ArrowUp')pitch-=.1;if(e.key==='ArrowDown')pitch+=.1;draw();}};
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;document.querySelectorAll('[data-mode]').forEach(q=>q.setAttribute('aria-pressed',String(q===b)));options();loadPreset();});$('preset').onchange=loadPreset;$('reset').onclick=loadPreset;$('fit').onclick=fit;
new ResizeObserver(entries=>{let rect=entries[0].contentRect,old=width;width=rect.width;height=rect.height;let dpr=window.devicePixelRatio||1;canvas.width=Math.round(width*dpr);canvas.height=Math.round(height*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);view.scale*=width/old;if(!data)fit();draw();}).observe(canvas.parentElement);options();coords();fit();request();
// Optional browser tool interface, sharing the coordinate controls' state.
if(document.modelContext?.registerTool){
 const lifecycle=new AbortController();window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});
 try{Promise.resolve(document.modelContext.registerTool({
  name:'set_attractive_center_configuration',description:'Set the explorer mode and vertex coordinates, and wait for the displayed regions to be computed.',
  annotations:{readOnlyHint:false,untrustedContentHint:false},
  inputSchema:{type:'object',properties:{mode:{enum:['triangle','four','tetra']},points:{type:'array',items:{type:'array',items:{type:'number'}}}},required:['mode','points'],additionalProperties:false},
  execute:async input=>{
   let dim=input?.mode==='tetra'?3:2,n=input?.mode==='triangle'?3:4;
   if(!presets[input?.mode]||!Array.isArray(input.points)||input.points.length!==n||!input.points.every(p=>Array.isArray(p)&&p.length===dim&&p.every(v=>Number.isFinite(v)&&Math.abs(v)<1e8)))throw Error('Invalid mode or coordinates');
   mode=input.mode;document.querySelectorAll('[data-mode]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.mode===mode)));
   options();points=structuredClone(input.points);data=null;coords();fit();request();const id=seq;
   await new Promise((resolve,reject)=>{
    let timer;const cleanup=()=>{clearTimeout(timer);worker.removeEventListener('message',handler);};
    const handler=({data:r})=>{if(r.id<id)return;cleanup();if(r.id!==id)reject(Error('Configuration changed during calculation'));else if(r.error)reject(Error(r.error));else resolve();};
    worker.addEventListener('message',handler);timer=setTimeout(()=>{cleanup();reject(Error('Calculation timed out'));},30000);
   });
   return {mode,points,regionVertices:mode==='triangle'?data.result.poly.length:mode==='four'?data.result.combined.length:data.result.vertices.length};
  }
 },{signal:lifecycle.signal})).catch(()=>{});}catch{}
}
