(() => {
  "use strict";

  const shell = document.querySelector("#atlas-shell");
  const rankRange = document.querySelector("#rank-range");
  const rankNumber = document.querySelector("#rank-number");
  const rankLabel = document.querySelector("#rank-label");
  const previousButton = document.querySelector("#previous-rank");
  const nextButton = document.querySelector("#next-rank");
  const copyLinkButton = document.querySelector("#copy-link");
  const searchForm = document.querySelector("#diagram-search");
  const searchInput = document.querySelector("#diagram-query");
  const searchResults = document.querySelector("#search-results");
  const diagramOptions = document.querySelector("#diagram-options");
  const cards = {
    interestingness: document.querySelector('[data-card="interestingness"]'),
    quadtree: document.querySelector('[data-card="quadtree"]')
  };

  const imageDialog = document.querySelector("#image-dialog");
  const dialogImage = document.querySelector("#dialog-image");
  const imageDialogTitle = document.querySelector("#image-dialog-title");
  const imageDialogCaption = document.querySelector("#image-dialog-caption");
  const imageDialogDownload = document.querySelector("#image-dialog-download");
  const zoomLevel = document.querySelector("#zoom-level");
  const zoomInButton = document.querySelector("#zoom-in");
  const zoomOutButton = document.querySelector("#zoom-out");

  const pdfDialog = document.querySelector("#pdf-dialog");
  const pdfFrame = document.querySelector("#pdf-frame");
  const pdfDialogTitle = document.querySelector("#pdf-dialog-title");
  const pdfOpenNew = document.querySelector("#pdf-open-new");
  const pdfDownload = document.querySelector("#pdf-download");

  let atlas = null;
  let currentRank = 1;
  let zoom = 1;
  let searchIndex = [];

  const format = {
    score: value => Number(value).toFixed(3),
    ratio: value => Number(value).toFixed(4),
    rank: value => `#${Number(value).toLocaleString("en-US")}`
  };

  function openDialog(dialog) {
    if (typeof dialog.showModal === "function") {
      dialog.showModal();
    } else {
      dialog.setAttribute("open", "");
    }
  }

  function closeDialog(dialog) {
    if (typeof dialog.close === "function") {
      dialog.close();
    } else {
      dialog.removeAttribute("open");
    }
  }

  function metricElement(label, value) {
    const wrapper = document.createElement("div");
    wrapper.className = "metric";
    const term = document.createElement("dt");
    const description = document.createElement("dd");
    term.textContent = label;
    description.textContent = value;
    wrapper.append(term, description);
    return wrapper;
  }

  function renderCard(card, diagram, side) {
    card._diagram = diagram;
    const isInterestingness = side === "interestingness";
    const primaryRank = isInterestingness ? diagram.interestingnessRank : diagram.quadtreeRank;
    const otherRank = isInterestingness ? diagram.quadtreeRank : diagram.interestingnessRank;
    const otherLabel = isInterestingness ? "Quadtree" : "Interestingness";

    card.querySelector('[data-field="primary-rank"]').textContent = format.rank(primaryRank);
    card.querySelector('[data-field="other-rank"]').textContent = `${otherLabel} ${format.rank(otherRank)}`;
    card.querySelector('[data-field="diagram-id"]').textContent = diagram.diagramId;
    card.querySelector('[data-field="definition"]').textContent = diagram.definition;

    const image = card.querySelector('[data-field="image"]');
    image.src = diagram.image;
    image.alt = `${diagram.diagramId}: a sixfold-symmetric triangle-space attractor generated by the ${diagram.mapName} map`;

    const openImageButton = card.querySelector('[data-action="open-image"]');
    openImageButton.setAttribute("aria-label", `Open the full-resolution ${diagram.diagramId} image`);

    const download = card.querySelector('[data-field="download"]');
    download.href = diagram.image;
    download.download = `${diagram.diagramId}_50k.png`;
    download.setAttribute("aria-label", `Download ${diagram.diagramId} as a full-resolution PNG`);

    const metrics = card.querySelector('[data-field="metrics"]');
    metrics.replaceChildren(
      metricElement("Neural interestingness", format.score(diagram.interestingnessScore)),
      metricElement("Quadtree Wundt gate", format.ratio(diagram.quadtreeGate)),
      metricElement("Quadtree / random", format.ratio(diagram.quadtreeRelativeToRandom)),
      metricElement("PNG / random", format.ratio(diagram.pngRelativeToRandom)),
      metricElement("Fitted taste", format.score(diagram.fittedTaste)),
      metricElement("Reference similarity", format.ratio(diagram.referenceSimilarity))
    );
  }

  function updateUrl(rank) {
    const url = new URL(window.location.href);
    url.searchParams.set("rank", String(rank));
    window.history.replaceState({ rank }, "", url);
  }

  function prefetchRank(rank) {
    if (!atlas || rank < 1 || rank > atlas.rankCount) return;
    const pair = atlas.pairs[rank - 1];
    [pair.interestingness.image, pair.quadtree.image].forEach(src => {
      const image = new Image();
      image.src = src;
    });
  }

  function setRank(value, options = {}) {
    if (!atlas) return;
    const parsed = Math.round(Number(value));
    if (!Number.isFinite(parsed)) return;
    currentRank = Math.min(atlas.rankCount, Math.max(1, parsed));
    const pair = atlas.pairs[currentRank - 1];

    rankRange.value = String(currentRank);
    rankNumber.value = String(currentRank);
    rankLabel.textContent = `${currentRank} of ${atlas.rankCount}`;
    previousButton.disabled = currentRank === 1;
    nextButton.disabled = currentRank === atlas.rankCount;

    renderCard(cards.interestingness, pair.interestingness, "interestingness");
    renderCard(cards.quadtree, pair.quadtree, "quadtree");
    updateUrl(currentRank);

    window.setTimeout(() => {
      prefetchRank(currentRank - 1);
      prefetchRank(currentRank + 1);
    }, 250);

    if (options.focusAtlas) {
      document.querySelector("#comparison-grid").scrollIntoView({ behavior: "smooth", block: "start" });
    }
  }

  function buildSearchIndex() {
    const entries = [];
    const seenOptions = new Set();
    atlas.pairs.forEach(pair => {
      [
        ["interestingness", pair.interestingness],
        ["quadtree", pair.quadtree]
      ].forEach(([side, diagram]) => {
        entries.push({
          rank: pair.rank,
          side,
          diagramId: diagram.diagramId,
          center: diagram.center,
          map: diagram.map
        });
        if (!seenOptions.has(diagram.diagramId)) {
          const option = document.createElement("option");
          option.value = diagram.diagramId;
          diagramOptions.append(option);
          seenOptions.add(diagram.diagramId);
        }
      });
    });
    searchIndex = entries;
  }

  function searchDiagrams(query) {
    const normalized = query.trim().toUpperCase().replace(/[()\s]/g, "");
    if (!normalized) return [];
    const numberMatch = normalized.match(/\d+/);
    const center = numberMatch ? Number(numberMatch[0]) : null;
    const exact = searchIndex.filter(entry => entry.diagramId === normalized);
    if (exact.length) return exact;
    return searchIndex.filter(entry => {
      if (normalized.startsWith("X") && entry.diagramId.startsWith(normalized)) return true;
      return center !== null && entry.center === center;
    });
  }

  function renderSearchResults(matches, query) {
    searchResults.replaceChildren();
    if (!matches.length) {
      searchResults.textContent = `No Top 120 diagram matches “${query}”.`;
      return;
    }

    const prefix = document.createElement("span");
    prefix.textContent = matches.length === 1 ? "Found:" : "Matches:";
    searchResults.append(prefix);

    matches.forEach(match => {
      const button = document.createElement("button");
      const listName = match.side === "interestingness" ? "interestingness" : "quadtree";
      button.type = "button";
      button.textContent = `${match.diagramId} · ${listName} rank ${match.rank}`;
      button.addEventListener("click", () => setRank(match.rank, { focusAtlas: true }));
      searchResults.append(button);
    });
  }

  function openImage(diagram) {
    zoom = 1;
    dialogImage.src = diagram.image;
    dialogImage.alt = `${diagram.diagramId}: full-resolution triangle-space attractor`;
    dialogImage.style.width = "100%";
    imageDialogTitle.textContent = diagram.diagramId;
    imageDialogCaption.textContent = `${diagram.definition} · 6,667 × 5,779 PNG`;
    imageDialogDownload.href = diagram.image;
    imageDialogDownload.download = `${diagram.diagramId}_50k.png`;
    zoomLevel.value = "100%";
    openDialog(imageDialog);
  }

  function setZoom(nextZoom) {
    zoom = Math.min(4, Math.max(0.25, nextZoom));
    dialogImage.style.width = `${zoom * 100}%`;
    zoomLevel.value = `${Math.round(zoom * 100)}%`;
  }

  function openPdf(path, title) {
    pdfDialogTitle.textContent = title;
    pdfFrame.src = path;
    pdfOpenNew.href = path;
    pdfDownload.href = path;
    openDialog(pdfDialog);
  }

  function bindEvents() {
    previousButton.addEventListener("click", () => setRank(currentRank - 1));
    nextButton.addEventListener("click", () => setRank(currentRank + 1));
    rankRange.addEventListener("input", event => setRank(event.target.value));
    rankNumber.addEventListener("change", event => setRank(event.target.value));
    rankNumber.addEventListener("keydown", event => {
      if (event.key === "Enter") {
        event.preventDefault();
        setRank(event.currentTarget.value);
      }
    });

    copyLinkButton.addEventListener("click", async () => {
      const url = new URL(window.location.href);
      url.searchParams.set("rank", String(currentRank));
      url.hash = "atlas";
      try {
        await navigator.clipboard.writeText(url.toString());
        copyLinkButton.textContent = "Link copied";
      } catch {
        window.prompt("Copy this rank link:", url.toString());
      }
      window.setTimeout(() => { copyLinkButton.textContent = "Copy rank link"; }, 1800);
    });

    searchForm.addEventListener("submit", event => {
      event.preventDefault();
      const query = searchInput.value;
      renderSearchResults(searchDiagrams(query), query);
    });

    Object.values(cards).forEach(card => {
      card.querySelector('[data-action="open-image"]').addEventListener("click", () => openImage(card._diagram));
    });

    zoomInButton.addEventListener("click", () => setZoom(zoom + 0.25));
    zoomOutButton.addEventListener("click", () => setZoom(zoom - 0.25));

    document.querySelectorAll("[data-pdf-preview]").forEach(button => {
      button.addEventListener("click", () => openPdf(button.dataset.pdfPreview, button.dataset.pdfTitle));
    });

    document.querySelectorAll("[data-dialog-close]").forEach(button => {
      button.addEventListener("click", () => closeDialog(document.querySelector(`#${button.dataset.dialogClose}`)));
    });

    [imageDialog, pdfDialog].forEach(dialog => {
      dialog.addEventListener("click", event => {
        if (event.target === dialog) closeDialog(dialog);
      });
    });

    pdfDialog.addEventListener("close", () => {
      pdfFrame.src = "about:blank";
    });

    window.addEventListener("keydown", event => {
      const editable = event.target.matches("input, textarea, select, [contenteditable]");
      const dialogOpen = imageDialog.open || pdfDialog.open;
      if (editable || dialogOpen) return;
      if (event.key === "ArrowLeft") setRank(currentRank - 1);
      if (event.key === "ArrowRight") setRank(currentRank + 1);
    });

    window.addEventListener("popstate", () => {
      const rank = Number(new URL(window.location.href).searchParams.get("rank"));
      if (rank) setRank(rank);
    });
  }

  async function initialize() {
    try {
      const response = await fetch("data/atlas.json");
      if (!response.ok) throw new Error(`Atlas data returned ${response.status}`);
      atlas = await response.json();
      buildSearchIndex();
      bindEvents();
      const requestedRank = Number(new URL(window.location.href).searchParams.get("rank"));
      setRank(requestedRank || 1);
      shell.setAttribute("aria-busy", "false");
    } catch (error) {
      shell.setAttribute("aria-busy", "false");
      shell.innerHTML = `<p class="noscript">The interactive atlas could not be loaded. ${error.message}</p>`;
      console.error(error);
    }
  }

  initialize();
})();
