import {mkdir,copyFile,writeFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
const root=fileURLToPath(new URL('../',import.meta.url)),dist=path.join(root,'dist');
await mkdir(path.join(dist,'src'),{recursive:true});
await mkdir(path.join(dist,'data'),{recursive:true});
await mkdir(path.join(dist,'research/etc_matching'),{recursive:true});
const files=['index.html','styles.css','icon.svg','LICENSE','THIRD_PARTY_NOTICES.md','LICENSE-ETC-TOOLS','src/math.js','src/worker.js','src/app.js','src/etc.js','src/etc-response.js','data/etc-matches.json','data/etc-matches.csv','data/etc-attractivity.csv','data/etc-attractivity-certificates.json','data/etc-positive-certificates.json'];
files.push('research/ETC_NEIGHBORS.md','research/etc_matching/certify_neighbors.py','research/etc_matching/prove_positive.py','research/Power_Centers_and_Hull_Power_Centers.tex','research/Power_Centers_and_Hull_Power_Centers.pdf');
for(const file of files)await copyFile(path.join(root,file),path.join(dist,file));
await writeFile(path.join(dist,'.nojekyll'),'');
console.log(`Built ${files.length} static files in ${dist}`);
