"""Regenerate the exact eliminant shared by Julia and the browser.

Requires SymPy 1.14. Formulas: RegularTetrahedralSections.wl,
SectionInvariantPair. z=mu^3*cos(3phi), x=mu^2, H=h^2.
"""
from pathlib import Path
import json
import sympy as s

ROOT = Path(__file__).resolve().parents[1]
x,z,H,p,r = s.symbols('x z H p r')
D=4-3*x-z
e1=3*(4-x); e2=12*D; e3=4*D**2
s1=2*(1+H)*e1**2-3*(1+2*H)*e2
s2=(1+H)**2*e1**4-3*(1+H)*(1+2*H)*e1**2*e2+3*(1+H)*(1+3*H)*e2**2-9*H*e1*e3
s3=(1+H)**3*e1**2*e2**2-(1+H)**2*(1+4*H)*e2**3-(1+H)**2*(1+4*H)*e1**3*e3+9*H*(1+H)*(1+2*H)*e1*e2*e3-27*H**3*e3**2
P=s.cancel(s2/s1**2); R=s.cancel(s3/s1**3)
ep=s.together(p-P).as_numer_denom()[0]
er=s.together(r-R).as_numer_denom()[0]
print('Computing resultant', flush=True)
res=s.resultant(ep,er,z)
factors=s.factor_list(res)[1]
core=next(f for f,n in factors if f.has(p) or f.has(r))
assert s.degree(core,x)==4
print('Core degrees:',s.degree(core,x),s.degree(core,H),flush=True)
def terms(poly, variables):
    return [[int(c),*powers] for powers,c in s.Poly(poly,*variables).terms()]
d,e=s.symbols('d e')
# Center shape invariants at the equilateral point to reduce cancellation.
core=s.Poly(core.subs({p:s.Rational(1,3)-d,r:s.Rational(1,27)-d/3+e}),x,H,d,e).clear_denoms()[1].primitive()[1].as_expr()
ep=s.Poly(ep.subs(p,s.Rational(1,3)-d),z,x,H,d).clear_denoms()[1].primitive()[1].as_expr()
payload={'variables':['x','H','d','e'],'core':terms(core,[x,H,d,e]),
         'recovery':terms(ep,[z,x,H,d]),
         'provenance':'Derived exactly from SectionInvariantPair; see scripts/derive.py'}
(ROOT/'coefficients.mjs').write_text('export const coefficients = '+json.dumps(payload,separators=(',',':'))+';\n')
(ROOT/'julia/src/coefficients.jl').write_text('# Generated by scripts/derive.py; columns: coefficient, powers.\nconst CORE = [\n'+''.join('    '+ ' '.join(map(str,t))+';\n' for t in payload['core'])+']\nconst RECOVERY = [\n'+''.join('    '+' '.join(map(str,t))+';\n' for t in payload['recovery'])+']\n')
(ROOT/'tests/eliminant.json').write_text(json.dumps(payload))
print('Wrote exact integer coefficients',flush=True)
