# Generated from the supplied ranked catalogue.
const catalogue = [
(rank=1, expression="TSY[2, TSA, TSB, TSC, TSZ[2]]", index=0.7692307692307692),
(rank=2, expression="TSZ[1]", index=1.0),
(rank=3, expression="TSZ[2]", index=1.0),
(rank=4, expression="TSZ[3]", index=1.0),
(rank=5, expression="TSY[1, TSX[2], TSX[3], TSZ[1], TSZ[2]]", index=1.25),
(rank=6, expression="TSY[2, TSA, TSB, TSC, TSZ[3]]", index=1.428571428571429),
(rank=7, expression="TSY[1, TSX[2], TSX[4], TSZ[1], TSZ[2]]", index=1.666666666666667),
(rank=8, expression="TSY[1, TSA, TSB, TSC, TSZ[2]]", index=2.0),
(rank=9, expression="TSY[1, TSA, TSB, TSC, TSZ[3]]", index=2.0),
(rank=10, expression="TSY[1, TSX[3], TSX[4], TSZ[1], TSZ[2]]", index=2.5),
(rank=11, expression="TSY[2, TSConjugate[TSZ[1]], TSX[4], TSZ[1], TSZ[2]]", index=2.5),
(rank=12, expression="TSY[2, TSConjugate[TSZ[1]], TSX[4], TSZ[1], TSZ[3]]", index=2.5),
(rank=13, expression="TSY[2, TSConjugate[TSZ[2]], TSX[1], TSX[4], TSZ[1]]", index=2.5),
(rank=14, expression="TSY[2, TSConjugate[TSZ[2]], TSX[2], TSX[4], TSZ[1]]", index=2.5),
(rank=15, expression="TSY[2, TSConjugate[TSZ[2]], TSX[3], TSX[4], TSZ[1]]", index=2.5),
(rank=16, expression="TSY[2, TSConjugate[TSZ[2]], TSX[4], TSZ[1], TSZ[3]]", index=2.5),
(rank=17, expression="TSY[2, TSConjugate[TSZ[3]], TSX[1], TSX[4], TSZ[1]]", index=2.5),
(rank=18, expression="TSY[2, TSConjugate[TSZ[3]], TSX[1], TSX[4], TSZ[2]]", index=2.5),
(rank=19, expression="TSY[2, TSConjugate[TSZ[3]], TSX[2], TSX[4], TSZ[1]]", index=2.5),
(rank=20, expression="TSY[2, TSConjugate[TSZ[3]], TSX[2], TSX[4], TSZ[2]]", index=2.5),
(rank=21, expression="TSY[2, TSConjugate[TSZ[3]], TSX[3], TSX[4], TSZ[1]]", index=2.5),
(rank=22, expression="TSY[2, TSConjugate[TSZ[3]], TSX[3], TSX[4], TSZ[2]]", index=2.5),
(rank=23, expression="TSY[2, TSConjugate[TSZ[3]], TSX[4], TSZ[1], TSZ[2]]", index=2.5),
(rank=24, expression="TSY[2, TSX[1], TSX[2], TSX[4], TSZ[3]]", index=2.5),
(rank=25, expression="TSY[2, TSX[1], TSX[3], TSX[4], TSZ[3]]", index=2.5),
(rank=26, expression="TSY[2, TSX[1], TSX[4], TSZ[1], TSZ[3]]", index=2.5),
(rank=27, expression="TSY[2, TSX[2], TSX[3], TSX[4], TSZ[3]]", index=2.5),
(rank=28, expression="TSY[2, TSX[2], TSX[4], TSZ[1], TSZ[3]]", index=2.5),
(rank=29, expression="TSY[2, TSX[3], TSX[4], TSZ[1], TSZ[3]]", index=2.5),
(rank=30, expression="TSY[1, TSA, TSB, TSC, TSY[1, TSA, TSB, TSC, TSZ[2]]]", index=3.0),
(rank=31, expression="TSY[1, TSA, TSB, TSC, TSY[1, TSA, TSB, TSC, TSZ[3]]]", index=3.0),
(rank=32, expression="TSY[1, TSA, TSB, TSC, TSY[2, TSA, TSB, TSC, TSZ[2]]]", index=3.0),
(rank=33, expression="TSY[1, TSA, TSB, TSC, TSY[2, TSA, TSB, TSC, TSZ[3]]]", index=3.0),
(rank=34, expression="TSY[2, TSA, TSB, TSC, TSY[1, TSA, TSB, TSC, TSZ[2]]]", index=3.0),
(rank=35, expression="TSY[2, TSA, TSB, TSC, TSY[1, TSA, TSB, TSC, TSZ[3]]]", index=3.0),
(rank=36, expression="TSY[2, TSA, TSB, TSC, TSY[2, TSA, TSB, TSC, TSZ[2]]]", index=3.0),
(rank=37, expression="TSY[2, TSA, TSB, TSC, TSY[2, TSA, TSB, TSC, TSZ[3]]]", index=3.0),
(rank=38, expression="TSY[1, TSA, TSB, TSC, TSY[1, TSA, TSB, TSC, TSY[1, TSA, TSB, TSC, TSZ[2]]]]", index=4.0),
(rank=39, expression="TSY[1, TSA, TSB, TSC, TSY[1, TSA, TSB, TSC, TSY[1, TSA, TSB, TSC, TSZ[3]]]]", index=4.0),
(rank=40, expression="TSY[1, TSA, TSB, TSC, TSY[1, TSA, TSB, TSC, TSY[2, TSA, TSB, TSC, TSZ[2]]]]", index=4.0),
(rank=41, expression="TSY[1, TSA, TSB, TSC, TSY[1, TSA, TSB, TSC, TSY[2, TSA, TSB, TSC, TSZ[3]]]]", index=4.0),
(rank=42, expression="TSY[1, TSA, TSB, TSC, TSY[2, TSA, TSB, TSC, TSY[1, TSA, TSB, TSC, TSZ[2]]]]", index=4.0),
(rank=43, expression="TSY[1, TSA, TSB, TSC, TSY[2, TSA, TSB, TSC, TSY[1, TSA, TSB, TSC, TSZ[3]]]]", index=4.0),
(rank=44, expression="TSY[1, TSA, TSB, TSC, TSY[2, TSA, TSB, TSC, TSY[2, TSA, TSB, TSC, TSZ[2]]]]", index=4.0),
(rank=45, expression="TSY[1, TSA, TSB, TSC, TSY[2, TSA, TSB, TSC, TSY[2, TSA, TSB, TSC, TSZ[3]]]]", index=4.0),
(rank=46, expression="TSY[2, TSA, TSB, TSC, TSY[1, TSA, TSB, TSC, TSY[1, TSA, TSB, TSC, TSZ[2]]]]", index=4.0),
(rank=47, expression="TSY[2, TSA, TSB, TSC, TSY[1, TSA, TSB, TSC, TSY[1, TSA, TSB, TSC, TSZ[3]]]]", index=4.0),
(rank=48, expression="TSY[2, TSA, TSB, TSC, TSY[1, TSA, TSB, TSC, TSY[2, TSA, TSB, TSC, TSZ[2]]]]", index=4.0),
(rank=49, expression="TSY[2, TSA, TSB, TSC, TSY[1, TSA, TSB, TSC, TSY[2, TSA, TSB, TSC, TSZ[3]]]]", index=4.0),
(rank=50, expression="TSY[2, TSA, TSB, TSC, TSY[2, TSA, TSB, TSC, TSY[1, TSA, TSB, TSC, TSZ[2]]]]", index=4.0),
(rank=51, expression="TSY[2, TSA, TSB, TSC, TSY[2, TSA, TSB, TSC, TSY[1, TSA, TSB, TSC, TSZ[3]]]]", index=4.0),
(rank=52, expression="TSY[2, TSA, TSB, TSC, TSY[2, TSA, TSB, TSC, TSY[2, TSA, TSB, TSC, TSZ[2]]]]", index=4.0),
(rank=53, expression="TSY[2, TSA, TSB, TSC, TSY[2, TSA, TSB, TSC, TSY[2, TSA, TSB, TSC, TSZ[3]]]]", index=4.0),
(rank=54, expression="TSConjugate[TSY[1, TSConjugate[TSZ[2]], TSConjugate[TSZ[3]], TSX[1], TSZ[1]]]", index=5.0),
(rank=55, expression="TSY[1, TSConjugate[TSZ[1]], TSX[1], TSZ[1], TSZ[2]]", index=5.0),
(rank=56, expression="TSY[1, TSConjugate[TSZ[1]], TSX[1], TSZ[1], TSZ[3]]", index=5.0),
(rank=57, expression="TSY[1, TSConjugate[TSZ[1]], TSX[3], TSZ[1], TSZ[3]]", index=5.0),
(rank=58, expression="TSY[1, TSConjugate[TSZ[2]], TSX[1], TSZ[1], TSZ[2]]", index=5.0),
(rank=59, expression="TSY[1, TSConjugate[TSZ[2]], TSX[1], TSZ[2], TSZ[3]]", index=5.0),
(rank=60, expression="TSY[1, TSConjugate[TSZ[3]], TSX[1], TSX[4], TSZ[2]]", index=5.0),
(rank=61, expression="TSY[1, TSConjugate[TSZ[3]], TSX[1], TSZ[1], TSZ[2]]", index=5.0),
(rank=62, expression="TSY[1, TSConjugate[TSZ[3]], TSX[1], TSZ[1], TSZ[3]]", index=5.0),
(rank=63, expression="TSY[1, TSConjugate[TSZ[3]], TSX[1], TSZ[2], TSZ[3]]", index=5.0),
(rank=64, expression="TSY[1, TSX[1], TSX[2], TSX[3], TSZ[1]]", index=5.0),
(rank=65, expression="TSY[1, TSX[1], TSX[2], TSX[3], TSZ[2]]", index=5.0),
(rank=66, expression="TSY[1, TSX[1], TSX[2], TSX[3], TSZ[3]]", index=5.0),
(rank=67, expression="TSY[1, TSX[1], TSX[2], TSX[4], TSZ[1]]", index=5.0),
(rank=68, expression="TSY[1, TSX[1], TSX[2], TSX[4], TSZ[2]]", index=5.0),
(rank=69, expression="TSY[1, TSX[1], TSX[2], TSX[4], TSZ[3]]", index=5.0),
(rank=70, expression="TSY[1, TSX[1], TSX[2], TSZ[1], TSZ[2]]", index=5.0),
(rank=71, expression="TSY[1, TSX[1], TSX[2], TSZ[2], TSZ[3]]", index=5.0),
(rank=72, expression="TSY[1, TSX[1], TSX[3], TSX[4], TSZ[1]]", index=5.0),
(rank=73, expression="TSY[1, TSX[1], TSX[3], TSX[4], TSZ[2]]", index=5.0),
(rank=74, expression="TSY[1, TSX[1], TSX[3], TSX[4], TSZ[3]]", index=5.0),
(rank=75, expression="TSY[1, TSX[1], TSX[3], TSZ[1], TSZ[2]]", index=5.0),
(rank=76, expression="TSY[1, TSX[1], TSX[3], TSZ[1], TSZ[3]]", index=5.0),
(rank=77, expression="TSY[1, TSX[1], TSX[3], TSZ[2], TSZ[3]]", index=5.0),
(rank=78, expression="TSY[1, TSX[1], TSX[4], TSZ[1], TSZ[2]]", index=5.0),
(rank=79, expression="TSY[1, TSX[1], TSX[4], TSZ[1], TSZ[3]]", index=5.0),
(rank=80, expression="TSY[1, TSX[1], TSX[4], TSZ[2], TSZ[3]]", index=5.0),
(rank=81, expression="TSY[1, TSX[1], TSZ[1], TSZ[2], TSZ[3]]", index=5.0),
(rank=82, expression="TSY[1, TSX[3], TSX[4], TSZ[2], TSZ[3]]", index=5.0),
(rank=83, expression="TSY[1, TSX[4], TSZ[1], TSZ[2], TSZ[3]]", index=5.0),
(rank=84, expression="TSY[2, TSConjugate[TSZ[1]], TSX[1], TSZ[1], TSZ[2]]", index=5.0),
(rank=85, expression="TSY[2, TSConjugate[TSZ[1]], TSX[1], TSZ[1], TSZ[3]]", index=5.0),
(rank=86, expression="TSY[2, TSConjugate[TSZ[1]], TSX[2], TSZ[1], TSZ[2]]", index=5.0),
(rank=87, expression="TSY[2, TSConjugate[TSZ[1]], TSX[2], TSZ[1], TSZ[3]]", index=5.0),
(rank=88, expression="TSY[2, TSConjugate[TSZ[1]], TSX[3], TSZ[1], TSZ[2]]", index=5.0),
(rank=89, expression="TSY[2, TSConjugate[TSZ[1]], TSX[3], TSZ[1], TSZ[3]]", index=5.0),
(rank=90, expression="TSY[2, TSConjugate[TSZ[1]], TSZ[1], TSZ[2], TSZ[3]]", index=5.0),
(rank=91, expression="TSY[2, TSConjugate[TSZ[2]], TSConjugate[TSZ[3]], TSX[1], TSZ[1]]", index=5.0),
(rank=92, expression="TSY[2, TSConjugate[TSZ[2]], TSConjugate[TSZ[3]], TSX[2], TSZ[1]]", index=5.0),
(rank=93, expression="TSY[2, TSConjugate[TSZ[2]], TSConjugate[TSZ[3]], TSX[3], TSZ[1]]", index=5.0),
(rank=94, expression="TSY[2, TSConjugate[TSZ[2]], TSX[1], TSX[2], TSZ[1]]", index=5.0),
(rank=95, expression="TSY[2, TSConjugate[TSZ[2]], TSX[1], TSX[3], TSZ[1]]", index=5.0),
(rank=96, expression="TSY[2, TSConjugate[TSZ[2]], TSX[1], TSZ[1], TSZ[2]]", index=5.0),
(rank=97, expression="TSY[2, TSConjugate[TSZ[2]], TSX[2], TSX[3], TSZ[1]]", index=5.0),
(rank=98, expression="TSY[2, TSConjugate[TSZ[2]], TSX[2], TSZ[1], TSZ[2]]", index=5.0),
(rank=99, expression="TSY[2, TSConjugate[TSZ[2]], TSX[3], TSZ[1], TSZ[2]]", index=5.0),
(rank=100, expression="TSY[2, TSConjugate[TSZ[2]], TSX[4], TSZ[2], TSZ[3]]", index=5.0),
(rank=101, expression="TSY[2, TSConjugate[TSZ[3]], TSX[1], TSX[2], TSZ[1]]", index=5.0),
(rank=102, expression="TSY[2, TSConjugate[TSZ[3]], TSX[1], TSX[3], TSZ[1]]", index=5.0),
(rank=103, expression="TSY[2, TSConjugate[TSZ[3]], TSX[1], TSZ[1], TSZ[3]]", index=5.0),
(rank=104, expression="TSY[2, TSConjugate[TSZ[3]], TSX[2], TSX[3], TSZ[1]]", index=5.0),
(rank=105, expression="TSY[2, TSConjugate[TSZ[3]], TSX[2], TSZ[1], TSZ[3]]", index=5.0),
(rank=106, expression="TSY[2, TSConjugate[TSZ[3]], TSX[3], TSZ[1], TSZ[3]]", index=5.0),
(rank=107, expression="TSY[2, TSConjugate[TSZ[3]], TSZ[1], TSZ[2], TSZ[3]]", index=5.0),
(rank=108, expression="TSY[2, TSX[1], TSX[2], TSX[3], TSZ[1]]", index=5.0),
(rank=109, expression="TSY[2, TSX[1], TSX[2], TSX[3], TSZ[2]]", index=5.0),
(rank=110, expression="TSY[2, TSX[1], TSX[2], TSX[3], TSZ[3]]", index=5.0),
(rank=111, expression="TSY[2, TSX[1], TSX[2], TSX[4], TSZ[1]]", index=5.0),
(rank=112, expression="TSY[2, TSX[1], TSX[2], TSX[4], TSZ[2]]", index=5.0),
(rank=113, expression="TSY[2, TSX[1], TSX[2], TSZ[1], TSZ[2]]", index=5.0),
(rank=114, expression="TSY[2, TSX[1], TSX[2], TSZ[1], TSZ[3]]", index=5.0),
(rank=115, expression="TSY[2, TSX[1], TSX[2], TSZ[2], TSZ[3]]", index=5.0),
(rank=116, expression="TSY[2, TSX[1], TSX[3], TSX[4], TSZ[1]]", index=5.0),
(rank=117, expression="TSY[2, TSX[1], TSX[3], TSX[4], TSZ[2]]", index=5.0),
(rank=118, expression="TSY[2, TSX[1], TSX[3], TSZ[1], TSZ[2]]", index=5.0),
(rank=119, expression="TSY[2, TSX[1], TSX[3], TSZ[1], TSZ[3]]", index=5.0),
(rank=120, expression="TSY[2, TSX[1], TSX[3], TSZ[2], TSZ[3]]", index=5.0),
(rank=121, expression="TSY[2, TSX[1], TSX[4], TSZ[1], TSZ[2]]", index=5.0),
(rank=122, expression="TSY[2, TSX[1], TSX[4], TSZ[2], TSZ[3]]", index=5.0),
(rank=123, expression="TSY[2, TSX[1], TSZ[1], TSZ[2], TSZ[3]]", index=5.0),
(rank=124, expression="TSY[2, TSX[2], TSX[3], TSX[4], TSZ[1]]", index=5.0),
(rank=125, expression="TSY[2, TSX[2], TSX[3], TSX[4], TSZ[2]]", index=5.0),
(rank=126, expression="TSY[2, TSX[2], TSX[3], TSZ[1], TSZ[2]]", index=5.0),
(rank=127, expression="TSY[2, TSX[2], TSX[3], TSZ[1], TSZ[3]]", index=5.0),
(rank=128, expression="TSY[2, TSX[2], TSX[3], TSZ[2], TSZ[3]]", index=5.0),
(rank=129, expression="TSY[2, TSX[2], TSX[4], TSZ[1], TSZ[2]]", index=5.0),
(rank=130, expression="TSY[2, TSX[2], TSX[4], TSZ[2], TSZ[3]]", index=5.0),
(rank=131, expression="TSY[2, TSX[2], TSZ[1], TSZ[2], TSZ[3]]", index=5.0),
(rank=132, expression="TSY[2, TSX[3], TSX[4], TSZ[1], TSZ[2]]", index=5.0),
(rank=133, expression="TSY[2, TSX[3], TSX[4], TSZ[2], TSZ[3]]", index=5.0),
(rank=134, expression="TSY[2, TSX[3], TSZ[1], TSZ[2], TSZ[3]]", index=5.0),
(rank=135, expression="TSY[2, TSX[4], TSZ[1], TSZ[2], TSZ[3]]", index=5.0),
(rank=136, expression="TSY[1, TSA, TSB, TSC, TSY[1, TSA, TSB, TSC, TSY[1, TSA, TSB, TSC, TSY[1, TSA, TSB, TSC, TSZ[2]]]]]", index=5.0),
(rank=137, expression="TSY[1, TSA, TSB, TSC, TSY[1, TSA, TSB, TSC, TSY[1, TSA, TSB, TSC, TSY[1, TSA, TSB, TSC, TSZ[3]]]]]", index=5.0),
(rank=138, expression="TSY[1, TSA, TSB, TSC, TSY[1, TSA, TSB, TSC, TSY[1, TSA, TSB, TSC, TSY[2, TSA, TSB, TSC, TSZ[2]]]]]", index=5.0),
(rank=139, expression="TSY[1, TSA, TSB, TSC, TSY[1, TSA, TSB, TSC, TSY[1, TSA, TSB, TSC, TSY[2, TSA, TSB, TSC, TSZ[3]]]]]", index=5.0),
(rank=140, expression="TSY[1, TSA, TSB, TSC, TSY[1, TSA, TSB, TSC, TSY[2, TSA, TSB, TSC, TSY[1, TSA, TSB, TSC, TSZ[2]]]]]", index=5.0),
(rank=141, expression="TSY[1, TSA, TSB, TSC, TSY[1, TSA, TSB, TSC, TSY[2, TSA, TSB, TSC, TSY[1, TSA, TSB, TSC, TSZ[3]]]]]", index=5.0),
(rank=142, expression="TSY[1, TSA, TSB, TSC, TSY[1, TSA, TSB, TSC, TSY[2, TSA, TSB, TSC, TSY[2, TSA, TSB, TSC, TSZ[2]]]]]", index=5.0),
(rank=143, expression="TSY[1, TSA, TSB, TSC, TSY[1, TSA, TSB, TSC, TSY[2, TSA, TSB, TSC, TSY[2, TSA, TSB, TSC, TSZ[3]]]]]", index=5.0),
(rank=144, expression="TSY[1, TSA, TSB, TSC, TSY[2, TSA, TSB, TSC, TSY[1, TSA, TSB, TSC, TSY[1, TSA, TSB, TSC, TSZ[2]]]]]", index=5.0),
(rank=145, expression="TSY[1, TSA, TSB, TSC, TSY[2, TSA, TSB, TSC, TSY[1, TSA, TSB, TSC, TSY[1, TSA, TSB, TSC, TSZ[3]]]]]", index=5.0),
(rank=146, expression="TSY[1, TSA, TSB, TSC, TSY[2, TSA, TSB, TSC, TSY[1, TSA, TSB, TSC, TSY[2, TSA, TSB, TSC, TSZ[2]]]]]", index=5.0),
(rank=147, expression="TSY[1, TSA, TSB, TSC, TSY[2, TSA, TSB, TSC, TSY[1, TSA, TSB, TSC, TSY[2, TSA, TSB, TSC, TSZ[3]]]]]", index=5.0),
(rank=148, expression="TSY[1, TSA, TSB, TSC, TSY[2, TSA, TSB, TSC, TSY[2, TSA, TSB, TSC, TSY[1, TSA, TSB, TSC, TSZ[2]]]]]", index=5.0),
(rank=149, expression="TSY[1, TSA, TSB, TSC, TSY[2, TSA, TSB, TSC, TSY[2, TSA, TSB, TSC, TSY[1, TSA, TSB, TSC, TSZ[3]]]]]", index=5.0),
(rank=150, expression="TSY[1, TSA, TSB, TSC, TSY[2, TSA, TSB, TSC, TSY[2, TSA, TSB, TSC, TSY[2, TSA, TSB, TSC, TSZ[2]]]]]", index=5.0),
(rank=151, expression="TSY[1, TSA, TSB, TSC, TSY[2, TSA, TSB, TSC, TSY[2, TSA, TSB, TSC, TSY[2, TSA, TSB, TSC, TSZ[3]]]]]", index=5.0),
(rank=152, expression="TSY[2, TSA, TSB, TSC, TSY[1, TSA, TSB, TSC, TSY[1, TSA, TSB, TSC, TSY[1, TSA, TSB, TSC, TSZ[2]]]]]", index=5.0),
(rank=153, expression="TSY[2, TSA, TSB, TSC, TSY[1, TSA, TSB, TSC, TSY[1, TSA, TSB, TSC, TSY[1, TSA, TSB, TSC, TSZ[3]]]]]", index=5.0),
(rank=154, expression="TSY[2, TSA, TSB, TSC, TSY[1, TSA, TSB, TSC, TSY[1, TSA, TSB, TSC, TSY[2, TSA, TSB, TSC, TSZ[2]]]]]", index=5.0),
(rank=155, expression="TSY[2, TSA, TSB, TSC, TSY[1, TSA, TSB, TSC, TSY[1, TSA, TSB, TSC, TSY[2, TSA, TSB, TSC, TSZ[3]]]]]", index=5.0),
(rank=156, expression="TSY[2, TSA, TSB, TSC, TSY[1, TSA, TSB, TSC, TSY[2, TSA, TSB, TSC, TSY[1, TSA, TSB, TSC, TSZ[2]]]]]", index=5.0),
(rank=157, expression="TSY[2, TSA, TSB, TSC, TSY[1, TSA, TSB, TSC, TSY[2, TSA, TSB, TSC, TSY[1, TSA, TSB, TSC, TSZ[3]]]]]", index=5.0),
(rank=158, expression="TSY[2, TSA, TSB, TSC, TSY[1, TSA, TSB, TSC, TSY[2, TSA, TSB, TSC, TSY[2, TSA, TSB, TSC, TSZ[2]]]]]", index=5.0),
(rank=159, expression="TSY[2, TSA, TSB, TSC, TSY[1, TSA, TSB, TSC, TSY[2, TSA, TSB, TSC, TSY[2, TSA, TSB, TSC, TSZ[3]]]]]", index=5.0),
(rank=160, expression="TSY[2, TSA, TSB, TSC, TSY[2, TSA, TSB, TSC, TSY[1, TSA, TSB, TSC, TSY[1, TSA, TSB, TSC, TSZ[2]]]]]", index=5.0),
(rank=161, expression="TSY[2, TSA, TSB, TSC, TSY[2, TSA, TSB, TSC, TSY[1, TSA, TSB, TSC, TSY[1, TSA, TSB, TSC, TSZ[3]]]]]", index=5.0),
(rank=162, expression="TSY[2, TSA, TSB, TSC, TSY[2, TSA, TSB, TSC, TSY[1, TSA, TSB, TSC, TSY[2, TSA, TSB, TSC, TSZ[2]]]]]", index=5.0),
(rank=163, expression="TSY[2, TSA, TSB, TSC, TSY[2, TSA, TSB, TSC, TSY[1, TSA, TSB, TSC, TSY[2, TSA, TSB, TSC, TSZ[3]]]]]", index=5.0),
(rank=164, expression="TSY[2, TSA, TSB, TSC, TSY[2, TSA, TSB, TSC, TSY[2, TSA, TSB, TSC, TSY[1, TSA, TSB, TSC, TSZ[2]]]]]", index=5.0),
(rank=165, expression="TSY[2, TSA, TSB, TSC, TSY[2, TSA, TSB, TSC, TSY[2, TSA, TSB, TSC, TSY[1, TSA, TSB, TSC, TSZ[3]]]]]", index=5.0),
(rank=166, expression="TSY[2, TSA, TSB, TSC, TSY[2, TSA, TSB, TSC, TSY[2, TSA, TSB, TSC, TSY[2, TSA, TSB, TSC, TSZ[2]]]]]", index=5.0),
(rank=167, expression="TSY[2, TSA, TSB, TSC, TSY[2, TSA, TSB, TSC, TSY[2, TSA, TSB, TSC, TSY[2, TSA, TSB, TSC, TSZ[3]]]]]", index=5.0),
]
